SGCAS/urls.py
from django.conf.urls import url, handler403
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.views.generic import TemplateView
from SGCAS.settings import base, desarrollo
# from django.contrib.auth.views import logout_then_login


handler403 = 'apps.rol.views.handler403'
# se asigna la nueva ruta de la vista creada para el error 403

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="account/index.html")),
    url(r'^account/', include('allauth.urls')),
    path('usuario/', include('apps.usuario.urls', namespace='usuario')),
    path('rol/', include(('apps.rol.urls', 'rol'), namespace='rol')),
    path('item/', include(('apps.item.urls', 'item'), namespace='item')),
    path('tipo_item/', include(('apps.tipo_item.urls', 'tipo_item'), namespace='tipo_item')),
    path('mensajes/', include(('apps.mensajes.urls', 'mensajes'), namespace='mensajes')),
    path('gestion-proyecto/', include(('apps.proyecto.urls', 'proyecto'), namespace='proyecto')),
    path('comite/', include(('apps.comite.urls', 'comite'), namespace='comite')),
    path('fase/', include(('apps.fase.urls', 'fase'), namespace='fase')),
    url(r'^faq/', login_required(TemplateView.as_view(template_name='faq.html'))),
    path('linea_base/', include(('apps.linea_base.urls', 'linea_base'), namespace='linea_base')),
]

if desarrollo.DEBUG:
    urlpatterns += static(desarrollo.MEDIA_URL, document_root=desarrollo.MEDIA_ROOT)
    # urlpatterns += static(desarrollo.STATIC_URL, document_root=base.STATIC_ROOT)

"""
    path("signup/", views.signup, name="account_signup"),
    path("login/", views.login, name="account_login"),
<<<<<<< HEAD

    path("logout/", views.logout, name="account_logout"),
>>>>>>> origin/guillermo

=======
<<<<<<< HEAD
    path('logout/', views.logout, name="account_logout"),
=======
    path("logout/", views.logout, name="account_logout"),
>>>>>>> origin/guillermo
>>>>>>> 9de1af86a9d6e911ed13280b7cc8d7d8dc58a668
    path("password/change/", views.password_change,
         name="account_change_password"),
    path("password/set/", views.password_set, name="account_set_password"),
    path("inactive/", views.account_inactive, name="account_inactive"),

    # E-mail
    path("email/", views.email, name="account_email"),
    path("confirm-email/", views.email_verification_sent,
         name="account_email_verification_sent"),
    re_path(r"^confirm-email/(?P<key>[-:\w]+)/$", views.confirm_email,
            name="account_confirm_email"),

    # password reset
    path("password/reset/", views.password_reset,
         name="account_reset_password"),
    path("password/reset/done/", views.password_reset_done,
         name="account_reset_password_done"),
    re_path(r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
            views.password_reset_from_key,
            name="account_reset_password_from_key"),
    path("password/reset/key/done/", views.password_reset_from_key_done,
         name="account_reset_password_from_key_done"),
"""

apps/fase/urls.py
from django.conf.urls import url
from apps.fase.views import *
from django.contrib.auth.decorators import login_required, permission_required
# === Importamos las vistas basadas en clases y en funciones del codigo fuente de views.py ===

urlpatterns = [
    url(r'^opciones/', login_required(fase_opciones), name='fase_opciones'),
    url(r'^results/(?P<_id>\d+)/$', login_required(permission_required('fase.listar_fase', raise_exception=True)(search)), name='search'),
    url(r'^cambiar_estado/(?P<id_fase>\d+)/(?P<_id>\d+)/$', login_required(cambiar_estado_fase), name='fase_cambiar_estado'),
    url(r'^fase_detalles/(?P<id_fase>\d+)/$', login_required(fase_detalles), name='fase_detalles'),
    url(r'^crear/(?P<_id>\d+)/$', login_required(permission_required('fase.crear_fase',raise_exception=True)(FaseCrear.as_view())), name='crear_fase'),
    url(r'^lista/(?P<_id>\d+)/$', login_required(permission_required('fase.listar_fase', raise_exception=True)(lista_fase)), name='fase_lista'),
    url(r'^eliminar/(?P<id_fase>\d+)/(?P<_id>\d+)/$', login_required(eliminar_fase), name='fase_eliminar'),
    url(r'^editar/(?P<id_fase>\d+)/(?P<_id>\d+)/$', login_required(fase_modificar), name='fase_modificar'),
    url(r'^generar-reporte/(?P<id_fase>\d+)/$', login_required(render_pdf_view), name='reporte_fase'),
]

# **Volver atras** : [[forms.py]]

# **Ir a la documentación de vistas del modulo fase** : [[views.py]]

# === Indice de la documentación de la Aplicación fase  === <br/>
# 1.admin   : [[admin.py]]<br/>
# 2.apps    : [[apps.py]]<br/>
# 3.forms   : [[forms.py]]<br/>
# 4.models  : [[models.py]]<br/>
# 5.tests   : [[tests.py]]<br/>
# 6.urls    : [[urls.py]]<br/>
# 7.views   : [[views.py]]<br/>

# Regresar al menu principal : [Menú Principal](../../docs-index/index.html)

apps/proyecto/urls.py
from django.urls import path, include
from django.conf.urls import url


from django.contrib.auth.decorators import login_required, permission_required
from apps.proyecto.views import manage_projects, CreateProject, ListProject, UpdateProject, DeleteProject, \
    success, DetailProject, change_state, search, render_pdf_view

app_name = 'proyecto'
# ** Dirección de URL desplegar las vistas en la dirección de plantillas respectivamente. **
urlpatterns = [
    path('', manage_projects, name='manage_projects'),
    url(r'^crear-proyecto/$', login_required(permission_required('proyecto.crear_proyecto', raise_exception=True)(CreateProject.as_view())), name='create'),
    url(r'^listado-proyecto/$', login_required(permission_required('proyecto.ver_proyecto', raise_exception=True)(ListProject.as_view())), name='list'),
    url(r'^results/$', login_required(permission_required('proyecto.ver_proyecto', raise_exception=True)(search)), name='search'),
    url(r'^editar-proyecto/(?P<pk>\d+)/$', login_required(permission_required('proyecto.editar_proyecto', raise_exception=True)(UpdateProject.as_view())), name='update'),
    url(r'^eliminar-proyecto/(?P<pk>\d+)/$', login_required(permission_required('proyecto.eliminar_proyecto', raise_exception=True)(DeleteProject.as_view())), name='delete'),
    url(r'^detalles-proyecto/(?P<pk>\d+)/$', login_required(permission_required('proyecto.detalles_proyecto', raise_exception=True)(DetailProject.as_view())), name='detail'),
    url(r'^operacion-exitosa/$', login_required(success), name='success'),
    url(r'^transicion-proyecto/(?P<pk>\d+)/$', login_required(change_state), name='change'),
url(r'^generar-reporte/(?P<id_proyecto>\d+)/$', login_required(render_pdf_view), name='reporte_items'),
]


# **Volver atras** : [[tests.py]]

# **Ir a la documentación de vistas de la Aplicación** :[[views.py]]

# === Indice de la documentación de la Aplicación Proyecto  === <br/>
# 1.admin   : [[admin.py]]<br/>
# 2.apps    : [[apps.py]]<br/>
# 3.forms   : [[forms.py]]<br/>
# 4.models  : [[models.py]]<br/>
# 5.tests   : [[tests.py]]<br/>
# 6.urls    : [[urls.py]]<br/>
# 7.views   : [[views.py]]<br/>

# Regresar al menu principal : [Menú Principal](../../docs-index/index.html)

apps/proyecto/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from guardian.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required

from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
# **Importamos los codigos fuentes de la aplicación para la creación de vistas
from SGCAS.decorators import requiere_permiso
from .models import Proyecto
from apps.fase.models import Fase
from apps.usuario.models import User

from django.db.models import Q
from django.core.paginator import Paginator
from .forms import FormularioProyecto, FormularioProyectoUpdate, ChangeProject
import datetime

from ..item.models import Item
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa

"""
Todas las vistas para la aplicación del Modulo Proyecto

Actualmente se despliega en las plantillas 9 vistas:

1. **manage_projects** - vista que despliega gestión de proyectos (Ir a la sección: [[views.py #manage_projects]] )<br/>
2. **success** - vista que despliega la operación exitosa de la definición de un proyecto (Ir a la sección: [[views.py #success]] )<br/>
3. **change_state** - vista que despliega el cambio de estado de un proyecto (Ir a la sección: [[views.py #change_state]] )<br/>
4. **CreateProject** - vista que despliega el formulario para definición de proyectos (Ir a la sección: [[views.py #create project]] )<br/>
5. **ListProject** - vista que despliega el listado de proyectos (Ir a la sección: [[views.py #list project]] )<br/>
6. **search** - vista que despliega una lista de proyectos buscados (Ir a la sección: [[views.py #search]] )<br/>
7. **UpdateProject** - vista que despliega la opción de actualizar un proyecto (Ir a la sección: [[views.py #update project]] )<br/>
8. **DeleteProject** - vista que despliega el borrado de un proyecto (Ir a la sección: [[views.py #delete project]] )<br/>
9. **DetailProject** - vista que despliega los detalles referentes a un proyecto (Ir a la sección: [[views.py #detail project]] )<br/>

"""


@login_required
@permission_required('proyecto.gestion_proyecto', raise_exception=True)
# === manage_projects ===
def manage_projects(request):
    """
    Recibe una petición a la pagina de proyecto por parte de un cliente, esta vista basada en una función retorna
    la pagina principal para la gestión de proyectos.<br/>
    **:param:** request<br/>
    **:return:** retorna la plantilla de gestión de proyectos<br/>
    """
    return render(request, 'proyecto/manage_projects.html')


@login_required
# === success ===
def success(request):
    """
    Una vista basada en función donde indica la creación exitosa de una operacion sobre proyectos.<br/>
    **:param request:** recibe la petición del cliente.<br/>
    **:return:** plantilla mostrando la operación exitosa.<br/>
    """
    return render(request, 'proyecto/success.html')


@login_required
@permission_required('proyecto.cambiar_estado', raise_exception=True)
# === change_state ===
def change_state(request, pk):
    """

    Vista basada en función donde desplegamos en una plantilla las diferentes transaciónes que pasa un proyecto.<br/>
    para el registro de sus cambios de estado.<br/>
    **:param request:** Solicitud del cliente para el cambio de estado.<br/>
    **:param pk:** Recibe la instancia del modelo proyecto a ser cambiado.<br/>
    **:return:** Realiza el cambio de estado , guarda en la base de datos y retorna el proyecto con su nuevo estado.<br/>
    """
    proyecto = get_object_or_404(Proyecto, id=pk)
    form = ChangeProject(request.POST or None, instance=proyecto)
    if proyecto.gerente == request.user:
        if form.is_valid():
            if proyecto.estado == 'Iniciado':
                proyecto.fecha_iniciado = datetime.date.today()
            elif proyecto.estado == 'Cancelado':
                proyecto.fecha_cancelado = datetime.date.today()
            elif proyecto.estado == 'Finalizado':
                proyecto.fecha_finalizado = datetime.date.today()
            proyecto.save()
            form.save()
            return redirect('proyecto:list')
        return render(request, 'proyecto/change.html', {'form': form, 'proyecto': proyecto})
    else:
        return render(request, 'proyecto/validate_estado_transicion.html')


# === create project ===
class CreateProject(CreateView, LoginRequiredMixin, PermissionRequiredMixin):
    """
    Permite la visualizacion en una plantilla para la definición de un proyecto.<br/>
    **:param PermissionRequiredMixin:** Libreria que gestiona el permiso para la creación de proyectos.El usuario
    debe poseer el permiso correspondiente de crear proyectos.<br/>
    **:param LoginRequiredMixin:** Requiere que el usuario este logueado en el sistema.<br/>
    **:param CreateView:** Recibe una vista generica de tipo CreateView para vistas basadas en clases.<br/>
    **:return:** Crea una instancia del modelo proyecto y lo guarda en la base de datos.<br/>
    """
    model = Proyecto
    form_class = FormularioProyecto
    permission_required = 'proyecto.crear_proyecto'
    template_name = 'proyecto/create.html'
    success_url = reverse_lazy('proyecto:success')

    # def get(self, request, **kwargs):
    #     ##revisar si existen usuarios en el sistema.
    #     ##si no existen, redirigir a un template que diga que no existen usuarios en el sistema
    #     ## si existen llamar get_form_kwargs(self, **kwargs)
        

    def get_form_kwargs(self, **kwargs):
        kwargs = super(CreateProject, self).get_form_kwargs(**kwargs)
        kwargs['gerente'] = self.request.user  # se envia al formulario el username del gerente
        return kwargs

    def form_valid(self, form):
        """
        Función de validación de los registros de un formulario y ademas guarda los datos que se obtuvieron en los cambpos en la base de datos<br/>
        **:param form:** recibe el formulario form<br/>
        **:return:** guarda los datos en la base de datos y redirige a una plantilla de Operación exitosa<br/>
        """
        self.object = form.save(commit=False)

        self.object.gerente = self.request.user  # intuimos que el creador del proyecto va ser el gerente

        self.object.save()
        form.save_m2m()  # Para guardar as relaciones manytomany
        return HttpResponseRedirect(self.get_success_url())


# === list project ===
class ListProject(ListView, LoginRequiredMixin, PermissionRequiredMixin):
    """
    Permite la visualizacion de los proyectos.<br/>
    **:param PermissionRequiredMixin:** Libreria que gestiona el permiso para la creación de proyectos.El usuario
    debe poseer el permiso correspondiente de visualizar proyectos.<br/>
    **:param LoginRequiredMixin:** Requiere estar logueado, de la libreria django.contrib.auth.mixins<br/>
    **:param ListView:** Recibe una vista generica de tipo ListView para vistas basadas en clases.<br/>
    **:return:** Una vista de todos los proyectos.<br/>
    """

    paginate_by = 4
    model = Proyecto
    permission_required = 'proyecto.ver_proyecto'
    template_name = 'proyecto/list.html'

    def get_queryset(self):
        # Queryset que muestra los proyectos del que el usuario forma parte
        return Proyecto.objects.filter(Q(gerente=self.request.user) | Q(miembros=self.request.user)).order_by(
            'id').distinct()


@permission_required('proyecto.ver_proyecto', raise_exception=True)
# === search ===
def search(request):
    """
    Permite la búsqueda de los proyectos.<br/>
    **:param request:** Recibe un request por parte de un usuario.<br/>
    **:return:** retorna una lista con los proyectos que cumplan con los criterios de búsqueda.<br/>
    """
    template = 'proyecto/list_busqueda.html'
    query = request.GET.get('buscar')

    if query:
        results = Proyecto.objects.filter((Q(gerente=request.user) | Q(miembros=request.user)) &
                                          (Q(nombre__icontains=query) | Q(descripcion__contains=query))).order_by(
            'id').distinct()
    else:
        results = Proyecto.objects.filter(Q(gerente=request.user) | Q(miembros=request.user)).order_by('id').distinct()

    paginator = Paginator(results, 4)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, template, {'page_obj': page_obj})


# === update project ===
class UpdateProject(LoginRequiredMixin, UpdateView, PermissionRequiredMixin):
    """
    Permite la actualizacion una instancia de modelo Proyecto.<br/>
    **:param PermissionRequiredMixin:** Libreria que gestiona el permiso para la creación de proyectos.El usuario
    debe poseer el permiso correspondiente de modificación de proyectos.<br/>
    **:param LoginRequiredMixin:** Requiere estar logueado, de la libreria django.contrib.auth.mixins<br/>
    **:param UpdateView:** Recibe una vista generica de tipo UpdateView para vistas basadas en clases.<br/>
    **:return:** Actualiza una instancia del modelo Proyecto, luego se redirige a la lista de proyectos.<br/>
    """
    model = Proyecto
    template_name = 'proyecto/update.html'
    form_class = FormularioProyectoUpdate
    permission_required = 'proyecto.editar_proyecto'

    def get_form_kwargs(self, **kwargs):
        kwargs = super(UpdateProject, self).get_form_kwargs(**kwargs)
        kwargs['gerente'] = self.request.user  # se envia al formulario el username del gerente
        return kwargs

    def form_valid(self, form):
        """

        Función que valida los campos requeridos fueron completados y los guarda en la base de datos.<br/>
        **:param form:** recibe el formulario con los datos.<br/>
        **:return:** redirige a la instancia del modelo proyecto en la plantilla de detalles de proyecto.<br/>

        """

templates/proyecto/create.html
{% extends 'base/base.html' %}
{% block title %} Crear proyecto {% endblock%}
{{ form.non_field_error }}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {#{ form.as_p }#}
        {% if error %}
            <h2>{{ error }}</h2>
        {% else %}
            <div class="card">
                <div class="card-header">
                    <strong>Formulario de Registro</strong>
                </div>
                <div class="card-body card-block">
                    <form action="#" method="post" enctype="multipart/form-data" class="form-horizontal">
                        <div class="row form-group">
                            <div class="col col-md-3">{{ form.nombre.label }}:</div>
                            <div class="col-12 col-md-9">{{ form.nombre }}</div>
                        </div>
                        <div class="row form-group">
                            <div class="col col-md-3">{{ form.descripcion.label }}:</div>
                            <div class="col-12 col-md-9">{{ form.descripcion }}</div>
                        </div>
                        <div class="row form-group">
                            <div class="col col-md-3">{{ form.estado.label }}:</div>
                            <div class="col-12 col-md-9">{{ form.estado }}</div>
                        </div>
                        <div class="row form-group">
                            <div class="col col-md-3">{{ form.fecha_creacion.label }}:</div>
                            <div class="col-12 col-md-9">{{ form.fecha_creacion }}</div>
                        </div>
                        <div class="row form-group">
                            <div class="col col-md-3">Agregar miembros al proyecto:</div>
                            <div class="">{{ form.miembros }}</div>
                        </div>
                        <div class="form-group">
                            <div class="text-center">
                                <button type="submit" class="btn btn-success">Crear</button>
                                <a type="button" class="btn btn-danger" href="{% url 'proyecto:manage_projects' %}">Cancelar</a>
                            </div>
                    </form>
                </div>
            </div>
        {% endif %}
    </form>
{% endblock %}

templates/proyecto/detail.html
{% extends 'base/base.html' %}
{% block title %} Detalles del proyecto {% endblock %}

{% block content %}
    <ol class="breadcrumb">
      <li class="breadcrumb-item active">Proyecto {{ object }} </li>
    </ol>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">Nombre del Proyecto</th>
            <th scope="col">Descripci&oacute;n del Proyecto</th>
            <th scope="col">Estado</th>
            <th scope="col">Miembros del Proyecto</th>
            <th scope="col">Fecha de creación</th>
            {% if proyecto.estado != 'Pendiente' %}
                <th scope="col">Fecha iniciada</th>
            {% endif %}
            {% if proyecto.estado == 'Cancelado' %}
                <th scope="col">Fecha Cancelada</th>
            {% endif %}
            {% if proyecto.estado == 'Finalizado' %}
                <th scope="col">Fecha Finalizada</th>
            {% endif %}
            <th scope="col">Ultima modificación</th>
        </tr>
        </thead>
        <tbody>
        {% if object %}
            <tr>
                <td>{{ object.nombre }}</td>
                <td>{{ object.descripcion }}</td>
                <td>{{ object.estado }}</td>
                <td>
                    {% for miembro in object.miembros.all %}
                     <li>{{ miembro }}</li>
                    {% endfor %}
                </td>
                <td>{{ object.fecha_creacion }}</td>
                 {% if proyecto.estado != 'Pendiente' %}
                     <th>{{ object.fecha_iniciado }}</th>
                 {% endif %}
                 {% if proyecto.estado == 'Cancelado' %}
                     <th>{{ object.fecha_cancelado }}</th>
                 {% endif %}
                 {% if proyecto.estado == 'Finalizado' %}
                     <th>{{ object.fecha_finalizado }}</th>
                 {% endif %}
                <td>{{ object.ultima_modificacion }}</td>
            </tr>
        {% else %}
            <h2>No se encontraron registros de proyectos.</h2>
        {% endif %}
        </tbody>
    </table>
    <a type="button" class="btn btn-secondary" href="{% url 'proyecto:list' %}">Salir</a>
    {% if proyecto.estado != 'Cancelado' and proyecto.estado != 'Finalizado'%}
        {% if request.user == proyecto.gerente %}

            <a type="button" class="btn btn-warning" href="{% url 'proyecto:update' proyecto.id %}">Modificar</a>

            {% if proyecto.estado != 'Iniciado'%}
                <a type="button" class="btn btn-danger" href="{% url 'proyecto:delete' proyecto.id %}">Eliminar</a>
            {% endif %}            

        {% endif %}
        <a type="button" class="btn btn-info" href="{% url 'comite:create' _id=proyecto.id %}">Comité</a>

            <div class="dropdown" style="display: inline">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
            Fases
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

            {% if proyecto.estado != 'Iniciado' %}

            <a class="dropdown-item" href="{% url 'fase:crear_fase' _id=proyecto.id %}">Crear fase</a>
            {% endif %}
            <a class="dropdown-item" href="{% url 'fase:fase_lista' proyecto.id %}">Lista de fases</a>
            {% if proyecto.estado == 'Iniciado' %}
            <a class="dropdown-item" href="{% url 'proyecto:reporte_items' proyecto.id %}">Reporte items</a>
            {% endif %}
        </div>
    </div>
    
    {% endif %}

{% endblock content %}

templates/proyecto/list.html
{% extends 'base/base.html' %}
{% block title %} Listar Proyectos {% endblock%}

{% block content %}
<form method="GET" action="{% url 'proyecto:search' %}">
        <div id="custom-search-input">
                    <div class="input-group col-md-12">
                        <input type="text" class="form-control search-users" placeholder="Ingrese el nombre o de la descripci&oacute;n del proyecto" name="buscar" value="{{ request.GET.buscar }}">
                        <span class="input-group-list">
                            <i class="icon icon-search"></i>
                            <button type="submit" class="btn btn-success btn-search-users">Buscar</button>
                        </span>
                    </div>
                </div>   
</form>

    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">Nombre del Proyecto</th>
            <!--<th scope="col">Descripci&oacute;n del Proyecto</th>-->
            <th scope="col">Gerente del Proyecto</th>
            <th scope="col">Estado</th>
        </tr>
        </thead>
        <tbody>
        {% if page_obj %}
            {% for proyecto in page_obj %}
                <tr>
                    <td>{{ proyecto.nombre }}</td>
                    <td>{{ proyecto.gerente }}</td>
                    <td>{{ proyecto.estado }}</td>
                    <td>
                        <a type="button" class="btn btn-info" href="{% url 'proyecto:detail' proyecto.id %}">Más
                            Detalles</a>
                        {% if proyecto.estado != 'Cancelado' and proyecto.estado != 'Finalizado'  %}
                            <a type="button" class="btn btn-info" href="{% url 'proyecto:change' proyecto.id %}">
                                Transici&oacute;n del Proyecto</a>                       
                        {% endif %}

                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <h2>No se encontraron registros de proyectos.</h2>
        {% endif %}
        </tbody>
    </table>
    <div class="text-center">
        <div class="pagination">
            <span class="step-links">
                
                <span class="current">
                      <li>Pagina {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</li>
                </span>
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; Inicio</a>
                    <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
                {% endif %}               

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>            
                {% endif %}
            </span>
        </div>
      </div>
    <a type="button" class="btn btn-secondary" href="{% url 'proyecto:manage_projects' %}">Regresar a Gestión de
        Proyectos</a>
{% endblock content %}

templates/proyecto/list_busqueda.html
{% extends 'base/base.html' %}
{% block title %} B&uacute;squeda de Proyectos {% endblock%}

{% block content %}
<form method="GET" action="{% url 'proyecto:search' %}">
        <div id="custom-search-input">
                    <div class="input-group col-md-12">
                        <input type="text" class="form-control search-users" placeholder="Ingrese el nombre o la descripci&oacute;n del proyecto" name="buscar" value="{{ request.GET.buscar }}">
                        <span class="input-group-list">
                            <i class="icon icon-search"></i>
                            <button type="submit" class="btn btn-success btn-search-users">Buscar</button>
                        </span>
                    </div>
                </div>   
</form>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">Nombre del Proyecto</th>
            <!--<th scope="col">Descripci&oacute;n del Proyecto</th>-->
            <th scope="col">Gerente del Proyecto</th>
            <th scope="col">Estado</th>
        </tr>
        </thead>
        <tbody>
        {% if page_obj %}
            {% for proyecto in page_obj %}
                <tr>
                    <td>{{ proyecto.nombre }}</td>
                    <td>{{ proyecto.gerente }}</td>
                    <td>{{ proyecto.estado }}</td>
                    <td>
                        <a type="button" class="btn btn-info" href="{% url 'proyecto:detail' proyecto.id %}">Más
                            Detalles</a>
                        {% if proyecto.estado != 'Cancelado' and proyecto.estado != 'Finalizado' %}
                            <a type="button" class="btn btn-info" href="{% url 'proyecto:change' proyecto.id %}">
                                Transici&oacute;n del Proyecto</a>
                        {% endif %}

                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <h2>No se encontraron registros de proyectos.</h2>
        {% endif %}
        </tbody>
    </table>

    <div class="text-center">
        <div class="pagination">
            <span class="step-links">
                
                <span class="current">
                      <li>Pagina {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</li>
                </span>
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; Inicio</a>
                    <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
                {% endif %}               

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>            
                {% endif %}
            </span>
        </div>
      </div>
      
    <a type="button" class="btn btn-secondary" href="{% url 'proyecto:list' %}">Regresar a Lista de
        Proyectos</a>
{% endblock content %}

templates/proyecto/manage_projects.html
{% extends 'base/base.html' %}

{% block title %} Gesti&oacute;n de Proyectos {% endblock %}

{% block content %}
    <br>
    <div class="list-group">
        <a href="{% url 'proyecto:create' %}" class="list-group-item list-group-item-action">Crear proyecto</a>
        <a href="{% url 'proyecto:list' %}" class="list-group-item list-group-item-action">Lista de proyectos</a>
    </div>
{% endblock content %}