SGCAS/urls.py
from django.conf.urls import url, handler403
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.views.generic import TemplateView
from SGCAS.settings import base, desarrollo
# from django.contrib.auth.views import logout_then_login


handler403 = 'apps.rol.views.handler403'
# se asigna la nueva ruta de la vista creada para el error 403

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="account/index.html")),
    url(r'^account/', include('allauth.urls')),
    path('usuario/', include('apps.usuario.urls', namespace='usuario')),
    path('rol/', include(('apps.rol.urls', 'rol'), namespace='rol')),
    path('item/', include(('apps.item.urls', 'item'), namespace='item')),
    path('tipo_item/', include(('apps.tipo_item.urls', 'tipo_item'), namespace='tipo_item')),
    path('mensajes/', include(('apps.mensajes.urls', 'mensajes'), namespace='mensajes')),
    path('gestion-proyecto/', include(('apps.proyecto.urls', 'proyecto'), namespace='proyecto')),
    path('comite/', include(('apps.comite.urls', 'comite'), namespace='comite')),
    path('fase/', include(('apps.fase.urls', 'fase'), namespace='fase')),
    url(r'^faq/', login_required(TemplateView.as_view(template_name='faq.html'))),
    path('linea_base/', include(('apps.linea_base.urls', 'linea_base'), namespace='linea_base')),
]

if desarrollo.DEBUG:
    urlpatterns += static(desarrollo.MEDIA_URL, document_root=desarrollo.MEDIA_ROOT)
    # urlpatterns += static(desarrollo.STATIC_URL, document_root=base.STATIC_ROOT)

"""
    path("signup/", views.signup, name="account_signup"),
    path("login/", views.login, name="account_login"),
<<<<<<< HEAD

    path("logout/", views.logout, name="account_logout"),
>>>>>>> origin/guillermo

=======
<<<<<<< HEAD
    path('logout/', views.logout, name="account_logout"),
=======
    path("logout/", views.logout, name="account_logout"),
>>>>>>> origin/guillermo
>>>>>>> 9de1af86a9d6e911ed13280b7cc8d7d8dc58a668
    path("password/change/", views.password_change,
         name="account_change_password"),
    path("password/set/", views.password_set, name="account_set_password"),
    path("inactive/", views.account_inactive, name="account_inactive"),

    # E-mail
    path("email/", views.email, name="account_email"),
    path("confirm-email/", views.email_verification_sent,
         name="account_email_verification_sent"),
    re_path(r"^confirm-email/(?P<key>[-:\w]+)/$", views.confirm_email,
            name="account_confirm_email"),

    # password reset
    path("password/reset/", views.password_reset,
         name="account_reset_password"),
    path("password/reset/done/", views.password_reset_done,
         name="account_reset_password_done"),
    re_path(r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
            views.password_reset_from_key,
            name="account_reset_password_from_key"),
    path("password/reset/key/done/", views.password_reset_from_key_done,
         name="account_reset_password_from_key_done"),
"""

apps/comite/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required

# === Importamos las vistas basadas en clases y en funciones del codigo fuente de views.py ===

# **Vistas basadas en clases**

# **1.CreateComite :** Vista que despliega la creación de un comité<br/>
# **2.UpdateComite :** Vista que despliega la modificación de un comité<br/>
# **3.DeleteComite :** Vista que despliega eliminar un comité<br/>
from apps.comite.views import CreateComite, UpdateComite, DeleteComite, success, lista_solicitudes, voto_favor, \
    voto_contra, DetailComite, auditoria_solicitudes, solicitud_item, DetailComite,reporte_solicitud_rango, render_pdf_view

app_name = 'comite'
# ** Dirección de URL desplegar las vistas en la dirección de plantillas respectivamente. **
urlpatterns = [
    url(r'^crear-comite/(?P<_id>\d+)/$', login_required(CreateComite.as_view()), name='create'),
    url(r'^editar-comite/(?P<pk>\d+)/$',login_required(permission_required('comite.editar_comite', raise_exception=True)(UpdateComite.as_view())),name='update'),
    url(r'^ver-comite/(?P<pk>\d+)/$',login_required(permission_required('comite.ver_comite', raise_exception=True)(DetailComite.as_view())),name='detail'),
    url(r'^eliminar-comite/(?P<pk>\d+)/$',login_required(permission_required('comite.eliminar_comite', raise_exception=True)(DeleteComite.as_view())),name='delete'),
    url(r'^detalles-comite/(?P<pk>\d+)/$',login_required(permission_required('comite.ver_comite', raise_exception=True)(DetailComite.as_view())),name='detail'),
    url(r'^operacion-exitosa/$', login_required(success), name='success'),
    url(r'^solicitud-item/(?P<pk>\d+)/$', login_required(solicitud_item), name='solicitud_item'),
    url(r'^lista-solicitudes/(?P<pk>\d+)/$', login_required(lista_solicitudes), name='solicitudes'),
    url(r'^voto_favor/(?P<pk>\d+)/$', login_required(voto_favor), name='voto_favor'),
    url(r'^voto_contra/(?P<pk>\d+)/$', login_required(voto_contra), name='voto_contra'),
    url(r'^auditoria-solicitudes/(?P<pk>\d+)/$', login_required(auditoria_solicitudes), name='auditoria'),
    url(r'^generar-reporte/(?P<id_proyecto>\d+)/(?P<id_comite>\d+)/$', login_required(render_pdf_view), name='reporte_solicitud'),
    url(r'^generar-reporte-por-rango/(?P<id_proyecto>\d+)/(?P<id_comite>\d+)/$', login_required(reporte_solicitud_rango), name='reporte_solicitud_rango'),
]

# **Atras** : [[tests.py]]

# **Siguiente** : [[views.py]]

# === Indice de la documentación de la Aplicación Comité  === <br/>
# 1.admin   : [[admin.py]]<br/>
# 2.apps    : [[apps.py]]<br/>
# 3.forms   : [[forms.py]]<br/>
# 4.models  : [[models.py]]<br/>
# 5.tests   : [[tests.py]]<br/>
# 6.urls    : [[urls.py]]<br/>
# 7.views   : [[views.py]]<br/>

# Regresar al menu principal : [Menú Principal](../../docs-index/index.html)

apps/item/urls.py
from django.conf.urls import url
from apps.item.views import *
from django.contrib.auth.decorators import login_required

# === Importamos las vistas basadas en clases y en funciones del codigo fuente de views.py ===

# **Vistas : **

# **1.Cambiar estado de un item :** Vista que despliega el cambio de estado de un item<br/>
# **2.Gestión de items          :** Vista que despliega la gestión de items<br/>
# **3.Crea item                 :** Vista que despliega la creación de un item<br/>
# **4.Importar tipo de item     :** Vista que despliega los tipos de items para importarlos<br/>
# **5.Atributos de un tipo_item :** Vista que despliega los atributos para un tipo de item<br/>
# **6.Listar items              :** Vista que despliega la lista de items en una fase<br/>
# **7.Eliminar item             :** Vista que despliega eliminar un item<br/>
# **8.Editar                    :** Vista que despliega editar un item<br/>
# **9.Editar tipo de item       :** Vista que despliega editar un tipo de item<br/>
# **10.Editar atributos         :** Vista que despliega editar los datos de un atributo de un tipo_item<br/>


# ** Dirección de URL desplegar las vistas en la dirección de plantillas respectivamente. **
urlpatterns = [
    url(r'^cambiar_estado/(?P<pk>\d+)/$', login_required(item_cambiar_estado), name='item_cambiar_estado'),
    url(r'^item_detalles/(?P<pk>\d+)/(?P<id_fase>\d+)/$', login_required(item_detalles), name='item_detalles'),
    url(r'^versiones/(?P<pk>\d+)/(?P<id_fase>\d+)/$', login_required(item_versiones), name='versiones'),
    url(r'^calculo-de-impacto/(?P<pk>\d+)/$', login_required(calculo_impacto), name='calculo_impacto'),
    url(r'^trazabilidad-de-item/(?P<pk>\d+)/$', login_required(trazabilidad), name='trazabilidad'),
    url(r'^restaurar_version/(?P<pk>\d+)/(?P<id_fase>\d+)/$', login_required(restaurar_version),
        name='restaurar_version'),
    url(r'^fases_relaciones/(?P<pk>\d+)/$', login_required(fases_rel), name='fases_rel'),
    url(r'^relaciones/(?P<pk>\d+)/(?P<id_fase>\d+)/$', login_required(relaciones), name='relaciones'),
    url(r'^crear/(?P<id_fase>\d+)/$', login_required(crear_item_basico), name='crear_item'),
    url(r'^importar_tipo_item/(?P<pk>\d+)/$', login_required(item_importar_ti), name='importar_tipo_item'),
    url(r'^atributos/(?P<pk>\d+)/$', login_required(item_set_atributos), name='set_atributos'),
    url(r'^results/(?P<id_fase>\d+)/$', login_required(search), name='search'),
    url(r'^lista/(?P<id_fase>\d+)/$', login_required(item_lista_fase), name='item_lista'),
    url(r'^eliminar/(?P<pk>\d+)/(?P<id_fase>\d+)/$', login_required(item_eliminar), name='item_eliminar'),
    url(r'^editar/(?P<pk>\d+)/(?P<id_fase>\d+)/$', login_required(item_modificar_basico), name='item_modificar'),
    url(r'^editar_import_ti/(?P<pk>\d+)/$', login_required(item_modificar_ti), name='item_modificar_import_ti'),
    url(r'^editar_atributos_ti/(?P<pk>\d+)/$', login_required(item_modificar_atributos), name='item_modificar_atr_ti'),
]
# **Atras** : [[tests.py]]

# **Siguiente** : [[views.py]]

# === Indice de la documentación de la Aplicación item  === <br/>
# 1.admin   : [[admin.py]]<br/>
# 2.apps    : [[apps.py]]<br/>
# 3.forms   : [[forms.py]]<br/>
# 4.models  : [[models.py]]<br/>
# 5.tests   : [[tests.py]]<br/>
# 6.urls    : [[urls.py]]<br/>
# 7.views   : [[views.py]]<br/>

# Regresar al menu principal : [Menú Principal](../../docs-index/index.html)

apps/proyecto/urls.py
from django.urls import path, include
from django.conf.urls import url


from django.contrib.auth.decorators import login_required, permission_required
from apps.proyecto.views import manage_projects, CreateProject, ListProject, UpdateProject, DeleteProject, \
    success, DetailProject, change_state, search, render_pdf_view

app_name = 'proyecto'
# ** Dirección de URL desplegar las vistas en la dirección de plantillas respectivamente. **
urlpatterns = [
    path('', manage_projects, name='manage_projects'),
    url(r'^crear-proyecto/$', login_required(permission_required('proyecto.crear_proyecto', raise_exception=True)(CreateProject.as_view())), name='create'),
    url(r'^listado-proyecto/$', login_required(permission_required('proyecto.ver_proyecto', raise_exception=True)(ListProject.as_view())), name='list'),
    url(r'^results/$', login_required(permission_required('proyecto.ver_proyecto', raise_exception=True)(search)), name='search'),
    url(r'^editar-proyecto/(?P<pk>\d+)/$', login_required(permission_required('proyecto.editar_proyecto', raise_exception=True)(UpdateProject.as_view())), name='update'),
    url(r'^eliminar-proyecto/(?P<pk>\d+)/$', login_required(permission_required('proyecto.eliminar_proyecto', raise_exception=True)(DeleteProject.as_view())), name='delete'),
    url(r'^detalles-proyecto/(?P<pk>\d+)/$', login_required(permission_required('proyecto.detalles_proyecto', raise_exception=True)(DetailProject.as_view())), name='detail'),
    url(r'^operacion-exitosa/$', login_required(success), name='success'),
    url(r'^transicion-proyecto/(?P<pk>\d+)/$', login_required(change_state), name='change'),
url(r'^generar-reporte/(?P<id_proyecto>\d+)/$', login_required(render_pdf_view), name='reporte_items'),
]


# **Volver atras** : [[tests.py]]

# **Ir a la documentación de vistas de la Aplicación** :[[views.py]]

# === Indice de la documentación de la Aplicación Proyecto  === <br/>
# 1.admin   : [[admin.py]]<br/>
# 2.apps    : [[apps.py]]<br/>
# 3.forms   : [[forms.py]]<br/>
# 4.models  : [[models.py]]<br/>
# 5.tests   : [[tests.py]]<br/>
# 6.urls    : [[urls.py]]<br/>
# 7.views   : [[views.py]]<br/>

# Regresar al menu principal : [Menú Principal](../../docs-index/index.html)

apps/comite/models/solicitud.py
from django.db import models
from apps.usuario.models import User
from apps.item.models import Item
from apps.linea_base.models import LineaBase
from apps.proyecto.models import Proyecto
import datetime

tipo_solicitud = [('Item', 'Item'), ('LineaBase', 'LineaBase')]

class Voto(models.Model):
	votante = models.ForeignKey(User, on_delete=models.DO_NOTHING)
	decision = models.BooleanField(default=True)
	fecha_voto = models.DateField(default=datetime.date.today)


class Solicitud(models.Model):
	asunto = models.CharField(max_length=100, default="")
	solicitante = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='solicitante', blank=True, null=True)
	votantes = models.ManyToManyField(User, blank=True)
	item = models.ForeignKey(Item, on_delete=models.CASCADE, blank=True, null=True)
	proyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE, blank=True, null=True)
	tipo = models.CharField(max_length=100, choices=tipo_solicitud, default='Item')
	linea_base = models.ForeignKey(LineaBase, on_delete=models.CASCADE, blank=True, null=True)
	fecha_solicitada = models.DateTimeField(auto_now_add=True)
	estado = models.CharField(max_length=15, default="En proceso")
	votacion = models.IntegerField(default=0)
	descripcion = models.TextField()
	auditoria = models.ManyToManyField(Voto,blank=True)
	en_proceso = models.BooleanField(default=True)
    



	def __str__(self):
		return self.asunto

apps/comite/forms.py
# === Importamos las librerias necesarias para la implementación de un Formulario ===
from django import forms
from .models import Comite, Solicitud
from ..proyecto.models import Proyecto
from ..linea_base.models import LineaBase
from ..item.models import Item
from django.shortcuts import get_object_or_404
from apps.item.views import get_lb


# === Clase para abstraer en un formulario el registro de un Comité ===
class FormularioComite(forms.ModelForm):
    # ** Formulario para el registro de comité **
    def __init__(self, *args, **kwargs):
        """
        Constructor que se encarga de filtrar solo los miembros de la instancia del proyecto la cual se desea crear
        un comité de aprobación.<br/>
        **:param args:**<br/>
        **:param kwargs:** diccionario de la referencia (_id) de la instancia del modelo proyecto<br/>
        """
        _id = kwargs.pop('_id')  # Se obtiene el id del proyecto a traves del kwargs
        super(FormularioComite, self).__init__(*args, **kwargs)  # Se inicializa el formulario
        self.fields['miembros'].queryset = Proyecto.objects.get(
            id=_id).miembros.all()  # Se filtra el queryset para miembros

    # **Clase Meta para para el despliegue en una plantilla de los campos necesarios del modelo**
    class Meta:
        model = Comite
        # **Campos requeridos para la definición de un comité**
        fields = [
            'nombre',
            'descripcion',
            'miembros',
        ]
        # **Etiquetas para el campo**
        labels = {
            'nombre': 'Asigne un nombre al comite del Proyecto',
            'descripcion': 'Descripción breve de responsabilidades de la comisión',
        }
        # **Aparatos para formatear un formulario con el respectivo campo**
        # Para obtener los datos y almacenar en la base de datos
        widgets = {

            'nombre': forms.TextInput(attrs={'class': 'form-control',
                                            'placeholder': 'Asigne un nombre al comité'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control',
                                            'placeholder': 'Agregue una breve descripción'}),

            'miembros': forms.CheckboxSelectMultiple(),
        }


# === Clase heredada para abstraer en un formulario la actualización de un Comité ===
class FormularioComiteUpdate(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(FormularioComiteUpdate, self).__init__(*args, **kwargs)
        self.fields['miembros'].queryset = kwargs['instance'].proyecto.miembros.all()

    class Meta(FormularioComite.Meta):
        model = Comite


class FormularioSolicitud(forms.ModelForm):
    def __init__(self, *args, **kwargs):             
        
        request = kwargs.pop('request') 
        pk = kwargs.pop('pk')      

        super(FormularioSolicitud, self).__init__(*args, **kwargs)
        fields_not_required = ['asunto', 'solicitante', 'item', 'tipo', 'linea_base', 'votacion','en_proceso','estado']
        
        self.fields['solicitante'].initial = request.user
        self.fields['proyecto'].initial = Item.objects.get(pk=pk).fase.proyecto
        

        for field in fields_not_required:
            self.fields[field].required = False
            self.fields[field].disabled = True

        
        self.fields['asunto'].initial = 'Item: {} | Fase: {} | Proyecto: {}.'.format( Item.objects.get(pk=pk),Item.objects.get(pk=pk).fase, Item.objects.get(pk=pk).fase.proyecto)
        self.fields['item'].initial = Item.objects.get(pk=pk)
        self.fields['linea_base'].initial = None

    class Meta:
        model = Solicitud
        fields = '__all__'
        labels = {'asunto':'Asunto', 'Descripción':'descripcion'}
        widgets = {
            'asunto': forms.TextInput(attrs={'class': 'form-control'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'placeholder':'Ingrese una descripción para la solicitud.'}),
        }


# **Volver atras** : [[apps.py]]

# **Ir a la documentación del modelo comité** : [[models.py]]

# === Indice de la documentación de la Aplicación Comité  === <br/>
# 1.admin   : [[admin.py]]<br/>
# 2.apps    : [[apps.py]]<br/>
# 3.forms   : [[forms.py]]<br/>
# 4.models  : [[models.py]]<br/>
# 5.tests   : [[tests.py]]<br/>
# 6.urls    : [[urls.py]]<br/>
# 7.views   : [[views.py]]<br/>

# Regresar al menu principal : [Menú Principal](../../docs-index/index.html)

templates/comite/alert.html
{% extends 'base/base.html' %}

{% block content %}
    <p align="center" class="badge badge-danger">Deben haber 3 usuarios como mínimo en el proyecto para crear comité</p>
    <br>
    <a type="button" class="btn btn-link" href="#" onclick="window.history.back()">Volver atr&aacute;s</a>
{% endblock content %}

templates/comite/detail.html
{% extends 'base/base.html' %}

{% block title %} Detalles del comit&eacute; {% endblock %}


{% block content %}
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'proyecto:detail' pk=comite.proyecto.pk %}">
      Proyecto {{ comite.proyecto }}</a></li>
      <li class="breadcrumb-item active">Comité {{ comite }}</li>
    </ol>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">Nombre del Comité</th>
            <th scope="col">Descripci&oacute;n del Comité</th>
            <th scope="col">Miembros del Comité</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ comite.nombre }}</td>
            <td>{{ comite.descripcion }}</td>
            <td>
                {% for miembro in comite.miembros.all %}
                    <li>{{ miembro }}</li>
                {% endfor %}
            </td>
        </tr>
        </tbody>
    </table>
    <a type="button" class="btn btn-secondary" href="{% url 'proyecto:detail' comite.proyecto.id %}">Regresar al Proyecto</a>
    {% if request.user.id == comite.proyecto.gerente_id %}
    <a type=" button" class="btn btn-warning" href="{% url 'comite:update' comite.id %}">Modificar</a>
    <a type="button" class="btn btn-danger" href="{% url 'comite:delete' comite.id %}">Eliminar</a>
    {% endif %}
    {# {% if request.user in comite.miembros.all %} #}
       <div class="dropdown" style="display: inline">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                    data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                Solicitudes
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item"
                   href="{% url 'comite:solicitudes' comite.id %}">Votacion</a>
            </div>
        </div>
    {# {% endif %} #}
{% endblock content %}

templates/comite/reporte_rango.html
{% extends 'base/base.html' %}
{% block title %}Solicitudes{% endblock%}

{% block content %}
    
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'proyecto:detail' pk=comite.proyecto.pk %}">Proyecto {{ comite.proyecto }}</a></li>
      <li class="breadcrumb-item"><a href="#" onclick="window.history.back()">Comité {{ comite }}</a></li>
      <li class="breadcrumb-item active">Solicitudes</li>
    </ol>
    
    <form method="POST" action="{% url 'comite:reporte_solicitud' id_proyecto id_comite %}">
        {% csrf_token %}
        <div class="card" style="padding-top: 50px; padding-left: 200px; padding-right: 200px">
            <div class="card-header">
                <strong>Generar reporte en un periodo de tiempo</strong>
            </div>
            <div class="card-body card-block">
                <form action="#" method="post" enctype="multipart/form-data" class="form-horizontal">
                    <div class="row form-group">
                        <div class="col col-md-3">Fecha de inicio</div>
                        <div class="col-12 col-md-9"><input type="date" name="fecha_inicio" id="fecha_inicio"></div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3">Fecha de fin</div>
                        <div class="col-12 col-md-9"><input type="date" name="fecha_fin" id="fecha_fin"></div>
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-secondary" onclick="return checkRange()">Generar reporte</button>
                        <a class="btn btn-secondary" href="#" onclick="window.history.back()">Cancelar</a>
                    </div>
                </form>
            </div>
        </div>
    </form>
    <script type="text/javascript">
        function checkRange(){
            var fecha_inicio = document.getElementById('fecha_inicio');
            var fecha_fin = document.getElementById('fecha_fin');

            console.log(fecha_inicio);
            console.log(fecha_fin);

            if (fecha_fin >= fecha_inicio){
                return true;
            }else{
                alert('La fecha de inicio debe de ser menor o igual a la fecha de fin')
                return false;    
            }
        }
    </script>
{% endblock content %}

templates/comite/solicitudes.html
{% extends 'base/base.html' %}
{% block title %}Solicitudes{% endblock%}

{% block extracss %}
    <script src="https://kit.fontawesome.com/aa90bcc874.js" crossorigin="anonymous"></script>
{% endblock %}

{% block content %}

    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'proyecto:detail' pk=comite.proyecto.pk %}">Proyecto {{ comite.proyecto }}</a></li>
      <li class="breadcrumb-item"><a href="#" onclick="window.history.back()">Comité {{ comite }}</a></li>
      <li class="breadcrumb-item active">Solicitudes</li>
    </ol>
    {% if page_obj %}
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">Artefacto</th>
                <th scope="col">Descripcion de la solicitud</th>
                <th scope="col">Fecha solicitada</th>
                <th scope="col">Solicitante</th>
      <!--      <th scope="col">Opciones</th>       -->
                <th scope="col">Decisi&oacute;n</th>
            </tr>
            </thead>
            <tbody>
                {% for solicitud in page_obj %}
                    <tr>
                        {% if solicitud.item %}
                            <td>Item</td>
                        {% else %}
                            <td>Linea Base</td>
                        {% endif %}
                        <td>{{ solicitud.descripcion }}</td>
                        <td>{{ solicitud.fecha_solicitada }}</td>
                        <td>{{ solicitud.solicitante }}</td>
                        <td>
<!--                        {% if solicitud.item %}
                                <a type="button" class="btn btn-secondary" href="{% url 'item:item_detalles' solicitud.item.id solicitud.item.fase.id %}">Detalles</a>
                            {% else %}
                                <a type="button" class="btn btn-secondary" href="#">Detalles</a>
                            {% endif %}     -->
                            {% if miembro_comite not in solicitud.votantes.all %}
                                {% if request.user != proyecto.gerente %}
                                       <div class="dropdown" style="display: inline">
                                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                                                    data-toggle="dropdown"
                                                    aria-haspopup="true" aria-expanded="false">
                                                Votar
                                            </button>
                                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                                <a class="dropdown-item" href="{% url 'comite:voto_favor' solicitud.id %}">A favor</a>
                                                <a class="dropdown-item" href="{% url 'comite:voto_contra' solicitud.id %}">En contra</a>
                                            </div>
                                        </div>
                                {% endif %}
                                <a type="button" class="btn btn-secondary" href="{% url 'comite:auditoria' solicitud.id %}">Auditoria</a>
                            {% else %}
                                <a type="button" class="btn btn-secondary" href="#">Votado <i class="fa fa-check" aria-hidden="true"></i></a>
                                <a type="button" class="btn btn-secondary" href="{% url 'comite:auditoria' solicitud.id %}">Auditoria</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

    <div class="text-center">
        <div class="pagination">
                <span class="step-links">

                    <span class="current">
                          <li>Pagina {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</li>
                    </span>
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; Inicio</a>
                        <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
                    {% endif %}

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                    {% endif %}
                </span>
        </div>
    </div>

    {% else %}
        <h2>No se encontraron solicitudes.</h2>
    {% endif %}
<a type="button" class="btn btn-secondary" href="{% url 'comite:detail' comite.id %}">Regresar a Detalles del comit&eacute;</a> 
<!-- <a type="button" class="btn btn-secondary" href="{% url 'comite:reporte_solicitud' comite.proyecto.id comite.id %}">Generar reporte de solicitudes</a> -->
                <div class="dropdown" style="display: inline">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                                    data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">
                                Generar reporte de solicitudes
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="{% url 'comite:reporte_solicitud' comite.proyecto.id comite.id %}">Todas las solicitudes</a>
                                <a class="dropdown-item" href="{% url 'comite:reporte_solicitud_rango' comite.proyecto.id comite.id %}">Por periodo de tiempo</a>
                            </div>
                        </div>
 <!--    <a type="button" class="btn btn-link" href="#" onclick="window.history.back()">Atrás</a>  -->
{% endblock content %}

templates/comite/success.html
{% extends 'base/base.html' %}


{% block content %}
	<h2>Operaci&oacute;n realizada con &eacute;xito !! </h2>
	<a type="button" class="btn btn-info" href="{% url 'proyecto:list'%}">Volver al listado de Proyectos</a>
{% endblock %}