SGCAS/urls.py
from django.conf.urls import url, handler403
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.views.generic import TemplateView
from SGCAS.settings import base, desarrollo
# from django.contrib.auth.views import logout_then_login


handler403 = 'apps.rol.views.handler403'
# se asigna la nueva ruta de la vista creada para el error 403

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="account/index.html")),
    url(r'^account/', include('allauth.urls')),
    path('usuario/', include('apps.usuario.urls', namespace='usuario')),
    path('rol/', include(('apps.rol.urls', 'rol'), namespace='rol')),
    path('item/', include(('apps.item.urls', 'item'), namespace='item')),
    path('tipo_item/', include(('apps.tipo_item.urls', 'tipo_item'), namespace='tipo_item')),
    path('mensajes/', include(('apps.mensajes.urls', 'mensajes'), namespace='mensajes')),
    path('gestion-proyecto/', include(('apps.proyecto.urls', 'proyecto'), namespace='proyecto')),
    path('comite/', include(('apps.comite.urls', 'comite'), namespace='comite')),
    path('fase/', include(('apps.fase.urls', 'fase'), namespace='fase')),
    url(r'^faq/', login_required(TemplateView.as_view(template_name='faq.html'))),
    path('linea_base/', include(('apps.linea_base.urls', 'linea_base'), namespace='linea_base')),
]

if desarrollo.DEBUG:
    urlpatterns += static(desarrollo.MEDIA_URL, document_root=desarrollo.MEDIA_ROOT)
    # urlpatterns += static(desarrollo.STATIC_URL, document_root=base.STATIC_ROOT)

"""
    path("signup/", views.signup, name="account_signup"),
    path("login/", views.login, name="account_login"),
<<<<<<< HEAD

    path("logout/", views.logout, name="account_logout"),
>>>>>>> origin/guillermo

=======
<<<<<<< HEAD
    path('logout/', views.logout, name="account_logout"),
=======
    path("logout/", views.logout, name="account_logout"),
>>>>>>> origin/guillermo
>>>>>>> 9de1af86a9d6e911ed13280b7cc8d7d8dc58a668
    path("password/change/", views.password_change,
         name="account_change_password"),
    path("password/set/", views.password_set, name="account_set_password"),
    path("inactive/", views.account_inactive, name="account_inactive"),

    # E-mail
    path("email/", views.email, name="account_email"),
    path("confirm-email/", views.email_verification_sent,
         name="account_email_verification_sent"),
    re_path(r"^confirm-email/(?P<key>[-:\w]+)/$", views.confirm_email,
            name="account_confirm_email"),

    # password reset
    path("password/reset/", views.password_reset,
         name="account_reset_password"),
    path("password/reset/done/", views.password_reset_done,
         name="account_reset_password_done"),
    re_path(r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
            views.password_reset_from_key,
            name="account_reset_password_from_key"),
    path("password/reset/key/done/", views.password_reset_from_key_done,
         name="account_reset_password_from_key_done"),
"""

apps/comite/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required

# === Importamos las vistas basadas en clases y en funciones del codigo fuente de views.py ===

# **Vistas basadas en clases**

# **1.CreateComite :** Vista que despliega la creación de un comité<br/>
# **2.UpdateComite :** Vista que despliega la modificación de un comité<br/>
# **3.DeleteComite :** Vista que despliega eliminar un comité<br/>
from apps.comite.views import CreateComite, UpdateComite, DeleteComite, success, lista_solicitudes, voto_favor, \
    voto_contra, DetailComite, auditoria_solicitudes, solicitud_item, DetailComite,reporte_solicitud_rango, render_pdf_view

app_name = 'comite'
# ** Dirección de URL desplegar las vistas en la dirección de plantillas respectivamente. **
urlpatterns = [
    url(r'^crear-comite/(?P<_id>\d+)/$', login_required(CreateComite.as_view()), name='create'),
    url(r'^editar-comite/(?P<pk>\d+)/$',login_required(permission_required('comite.editar_comite', raise_exception=True)(UpdateComite.as_view())),name='update'),
    url(r'^ver-comite/(?P<pk>\d+)/$',login_required(permission_required('comite.ver_comite', raise_exception=True)(DetailComite.as_view())),name='detail'),
    url(r'^eliminar-comite/(?P<pk>\d+)/$',login_required(permission_required('comite.eliminar_comite', raise_exception=True)(DeleteComite.as_view())),name='delete'),
    url(r'^detalles-comite/(?P<pk>\d+)/$',login_required(permission_required('comite.ver_comite', raise_exception=True)(DetailComite.as_view())),name='detail'),
    url(r'^operacion-exitosa/$', login_required(success), name='success'),
    url(r'^solicitud-item/(?P<pk>\d+)/$', login_required(solicitud_item), name='solicitud_item'),
    url(r'^lista-solicitudes/(?P<pk>\d+)/$', login_required(lista_solicitudes), name='solicitudes'),
    url(r'^voto_favor/(?P<pk>\d+)/$', login_required(voto_favor), name='voto_favor'),
    url(r'^voto_contra/(?P<pk>\d+)/$', login_required(voto_contra), name='voto_contra'),
    url(r'^auditoria-solicitudes/(?P<pk>\d+)/$', login_required(auditoria_solicitudes), name='auditoria'),
    url(r'^generar-reporte/(?P<id_proyecto>\d+)/(?P<id_comite>\d+)/$', login_required(render_pdf_view), name='reporte_solicitud'),
    url(r'^generar-reporte-por-rango/(?P<id_proyecto>\d+)/(?P<id_comite>\d+)/$', login_required(reporte_solicitud_rango), name='reporte_solicitud_rango'),
]

# **Atras** : [[tests.py]]

# **Siguiente** : [[views.py]]

# === Indice de la documentación de la Aplicación Comité  === <br/>
# 1.admin   : [[admin.py]]<br/>
# 2.apps    : [[apps.py]]<br/>
# 3.forms   : [[forms.py]]<br/>
# 4.models  : [[models.py]]<br/>
# 5.tests   : [[tests.py]]<br/>
# 6.urls    : [[urls.py]]<br/>
# 7.views   : [[views.py]]<br/>

# Regresar al menu principal : [Menú Principal](../../docs-index/index.html)

apps/fase/urls.py
from django.conf.urls import url
from apps.fase.views import *
from django.contrib.auth.decorators import login_required, permission_required
# === Importamos las vistas basadas en clases y en funciones del codigo fuente de views.py ===

urlpatterns = [
    url(r'^opciones/', login_required(fase_opciones), name='fase_opciones'),
    url(r'^results/(?P<_id>\d+)/$', login_required(permission_required('fase.listar_fase', raise_exception=True)(search)), name='search'),
    url(r'^cambiar_estado/(?P<id_fase>\d+)/(?P<_id>\d+)/$', login_required(cambiar_estado_fase), name='fase_cambiar_estado'),
    url(r'^fase_detalles/(?P<id_fase>\d+)/$', login_required(fase_detalles), name='fase_detalles'),
    url(r'^crear/(?P<_id>\d+)/$', login_required(permission_required('fase.crear_fase',raise_exception=True)(FaseCrear.as_view())), name='crear_fase'),
    url(r'^lista/(?P<_id>\d+)/$', login_required(permission_required('fase.listar_fase', raise_exception=True)(lista_fase)), name='fase_lista'),
    url(r'^eliminar/(?P<id_fase>\d+)/(?P<_id>\d+)/$', login_required(eliminar_fase), name='fase_eliminar'),
    url(r'^editar/(?P<id_fase>\d+)/(?P<_id>\d+)/$', login_required(fase_modificar), name='fase_modificar'),
    url(r'^generar-reporte/(?P<id_fase>\d+)/$', login_required(render_pdf_view), name='reporte_fase'),
]

# **Volver atras** : [[forms.py]]

# **Ir a la documentación de vistas del modulo fase** : [[views.py]]

# === Indice de la documentación de la Aplicación fase  === <br/>
# 1.admin   : [[admin.py]]<br/>
# 2.apps    : [[apps.py]]<br/>
# 3.forms   : [[forms.py]]<br/>
# 4.models  : [[models.py]]<br/>
# 5.tests   : [[tests.py]]<br/>
# 6.urls    : [[urls.py]]<br/>
# 7.views   : [[views.py]]<br/>

# Regresar al menu principal : [Menú Principal](../../docs-index/index.html)

apps/item/urls.py
from django.conf.urls import url
from apps.item.views import *
from django.contrib.auth.decorators import login_required

# === Importamos las vistas basadas en clases y en funciones del codigo fuente de views.py ===

# **Vistas : **

# **1.Cambiar estado de un item :** Vista que despliega el cambio de estado de un item<br/>
# **2.Gestión de items          :** Vista que despliega la gestión de items<br/>
# **3.Crea item                 :** Vista que despliega la creación de un item<br/>
# **4.Importar tipo de item     :** Vista que despliega los tipos de items para importarlos<br/>
# **5.Atributos de un tipo_item :** Vista que despliega los atributos para un tipo de item<br/>
# **6.Listar items              :** Vista que despliega la lista de items en una fase<br/>
# **7.Eliminar item             :** Vista que despliega eliminar un item<br/>
# **8.Editar                    :** Vista que despliega editar un item<br/>
# **9.Editar tipo de item       :** Vista que despliega editar un tipo de item<br/>
# **10.Editar atributos         :** Vista que despliega editar los datos de un atributo de un tipo_item<br/>


# ** Dirección de URL desplegar las vistas en la dirección de plantillas respectivamente. **
urlpatterns = [
    url(r'^cambiar_estado/(?P<pk>\d+)/$', login_required(item_cambiar_estado), name='item_cambiar_estado'),
    url(r'^item_detalles/(?P<pk>\d+)/(?P<id_fase>\d+)/$', login_required(item_detalles), name='item_detalles'),
    url(r'^versiones/(?P<pk>\d+)/(?P<id_fase>\d+)/$', login_required(item_versiones), name='versiones'),
    url(r'^calculo-de-impacto/(?P<pk>\d+)/$', login_required(calculo_impacto), name='calculo_impacto'),
    url(r'^trazabilidad-de-item/(?P<pk>\d+)/$', login_required(trazabilidad), name='trazabilidad'),
    url(r'^restaurar_version/(?P<pk>\d+)/(?P<id_fase>\d+)/$', login_required(restaurar_version),
        name='restaurar_version'),
    url(r'^fases_relaciones/(?P<pk>\d+)/$', login_required(fases_rel), name='fases_rel'),
    url(r'^relaciones/(?P<pk>\d+)/(?P<id_fase>\d+)/$', login_required(relaciones), name='relaciones'),
    url(r'^crear/(?P<id_fase>\d+)/$', login_required(crear_item_basico), name='crear_item'),
    url(r'^importar_tipo_item/(?P<pk>\d+)/$', login_required(item_importar_ti), name='importar_tipo_item'),
    url(r'^atributos/(?P<pk>\d+)/$', login_required(item_set_atributos), name='set_atributos'),
    url(r'^results/(?P<id_fase>\d+)/$', login_required(search), name='search'),
    url(r'^lista/(?P<id_fase>\d+)/$', login_required(item_lista_fase), name='item_lista'),
    url(r'^eliminar/(?P<pk>\d+)/(?P<id_fase>\d+)/$', login_required(item_eliminar), name='item_eliminar'),
    url(r'^editar/(?P<pk>\d+)/(?P<id_fase>\d+)/$', login_required(item_modificar_basico), name='item_modificar'),
    url(r'^editar_import_ti/(?P<pk>\d+)/$', login_required(item_modificar_ti), name='item_modificar_import_ti'),
    url(r'^editar_atributos_ti/(?P<pk>\d+)/$', login_required(item_modificar_atributos), name='item_modificar_atr_ti'),
]
# **Atras** : [[tests.py]]

# **Siguiente** : [[views.py]]

# === Indice de la documentación de la Aplicación item  === <br/>
# 1.admin   : [[admin.py]]<br/>
# 2.apps    : [[apps.py]]<br/>
# 3.forms   : [[forms.py]]<br/>
# 4.models  : [[models.py]]<br/>
# 5.tests   : [[tests.py]]<br/>
# 6.urls    : [[urls.py]]<br/>
# 7.views   : [[views.py]]<br/>

# Regresar al menu principal : [Menú Principal](../../docs-index/index.html)

apps/rol/urls.py
# === Importamos las vistas basadas en clases y en funciones del codigo fuente de views.py ===
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import Group
from apps.rol.views import crear_rol_view_sistema, lista_rol, search, editar_rol, eliminar_rol, asignar_rol_usuario
from apps.rol.views import crear_rol_view, rol_opciones_sistema, ListaRol_sistema, EditarRol_sistema, \
    EliminarRol_sistema, search_sistema, Usuario_roles

# **Vistas**


# **1.lista :** Vista que despliega la lista de roles existentes en el sistema<br/>
# **2.eliminar rol :** Vista que despliega eliminar un rol<br/>
# **3.crear rol :** Vista que despliega la definición de un rol<br/>
# **4.modificar rol :** Vista que despliega modificar un rol<br/>
# **5.search :** Vista que despliega una lista de roles buscados.<br/>
urlpatterns = [
    # ** Dirección de URL desplegar las vistas en la dirección de plantillas respectivamente. **

    url(r'^lista/(?P<id_fase>\d+)/$', login_required(lista_rol), name='rol_lista'),
    url(r'^eliminar-rol/(?P<pk>\d+)/(?P<id_fase>\d+)/$', login_required(eliminar_rol), name='rol_eliminar'),
    url(r'^crear/(?P<id_fase>\d+)/$', login_required(crear_rol_view), name='rol_crear'),
    url(r'^modificar-rol/(?P<pk>\d+)/(?P<id_fase>\d+)/$', login_required(editar_rol), name='rol_editar'),
    url(r'^results/(?P<id_fase>\d+)/$', login_required(search), name='search'),
    url(r'^asignar/(?P<pk>\d+)/(?P<id_fase>\d+)/$', login_required(asignar_rol_usuario), name='rol_asignar_usuario'),
    #=== ROL SISTEMA ===
    url(r'^opciones/', login_required(permission_required('rol.gestion_rol_sistema', raise_exception=True)(rol_opciones_sistema)), name='rol_opciones_sistema'),
    url(r'^lista/', login_required(permission_required('rol.listar_rol_sistema', raise_exception=True)(ListaRol_sistema.as_view())), name='rol_lista_sistema'),
    url(r'^results/$', login_required(permission_required('rol.listar_rol_sistema', raise_exception=True)(search_sistema)), name='search_sistema'),
    url(r'^eliminar/(?P<pk>\d+)/$', login_required(permission_required('rol.eliminar_rol_sistema', raise_exception=True)(EliminarRol_sistema.as_view())), name='rol_eliminar_sistema'),
    url(r'^crear/', login_required(permission_required('rol.crear_rol_sistema', raise_exception=True)(crear_rol_view_sistema)), name='rol_crear_sistema'),
    url(r'^modificar/(?P<pk>\d+)/$', login_required(permission_required('rol.editar_rol_sistema', raise_exception=True)(EditarRol_sistema.as_view(model=Group, ))), name='rol_editar_sistema'),
    
    url(r'^usuario-roles/', login_required(Usuario_roles.as_view()), name='usuario_rol'),
    # === FIN ====
]

# === Indice de la documentación de la Aplicación rol  === <br/>
# 1.apps     : [[apps.py]]<br/>
# 2.forms    : [[forms.py]]<br/>
# 3.tests    : [[tests.py]]<br/>
# 4.urls     : [[urls.py]]<br/>
# 5.views    : [[views.py]]<br/>

# Regresar al menu principal : [Menú Principal](../../docs-index/index.html)

apps/tipo_item/urls.py
# === Importamos las vistas basadas en clases y en funciones del codigo fuente de views.py ===
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required
from apps.tipo_item.views import tipo_item_opciones, crear_tipo_item, eliminar_tipo_item, \
    editar_tipo_item, search, tipo_item_lista, listar_importar_item, tipo_item_importar

# **Vistas basadas en clases**

# **1.Opciones :** Vista que despliega la gestión de tipo de item<br/>
# **2.Crear tipo item :** Vista que despliega la creación de un tipo de item<br/>
# **3.Listar tipo de item :** Vista que despliega la lista de tipo de item<br/>
# **4.Eliminar tipo de item :** Vista que despliega eliminar tipo de item<br/>
# **5.Editar tipo de item :** Vista que despliega edicion de un tipo de item<br/>
urlpatterns = [
    url(r'^opciones/', login_required(tipo_item_opciones), name='tipo_item_opciones'),
    url(r'^crear-tipo-item/(?P<id_fase>\d+)/$', login_required(crear_tipo_item), name='crear_tipo_item'),
    url(r'^lista-tipo-item/(?P<id_fase>\d+)/$', login_required(tipo_item_lista), name='tipo_item_lista'),
    url(r'^importar-item/(?P<id_fase>\d+)/$', login_required(listar_importar_item), name='listar_importacion'),
    url(r'^importar/(?P<id_proyecto>\d+)/(?P<id_item>\d+)/(?P<id_fase>\d+)/$', login_required(tipo_item_importar), name='importar'),
    url(r'^editar-tipo-item/(?P<id_item>\d+)/$', login_required(editar_tipo_item), name='tipo_item_modificar'),
    url(r'^eliminar-tipo-item/(?P<pk>\d+)/$', login_required(eliminar_tipo_item), name='tipo_item_eliminar'),
    url(r'^results/(?P<id_fase>\d+)/$', login_required(search), name='search'),    
]

# === Indice de la documentación de la Aplicación Comité  === <br/>
# 1.apps    : [[apps.py]]<br/>
# 2.forms   : [[forms.py]]<br/>
# 3.models  : [[models.py]]<br/>
# 4.tests   : [[tests.py]]<br/>
# 5.urls    : [[urls.py]]<br/>
# 6.views   : [[views.py]]<br/>

# Regresar al menu principal : [Menú Principal](../../docs-index/index.html)

templates/fase/fase_cambiar_estado.html
{% extends 'base/base.html' %}
{% block title %} Cambiar estado {% endblock%}

{% block content %}
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'proyecto:detail' pk=proyecto.pk %}">
      Proyecto {{ proyecto }}</a></li>  
      <li class="breadcrumb-item active">Fase {{ fase }} </li>        
    </ol>
        {% if error or fase.proyecto.estado == "Pendiente"%}
            <h2>{{ error }}</h2>
            <div class="alert alert-dismissible alert-warning">
                <button type="button" class="close" data-dismiss="alert" onclick="window.history.back()">&times;</button>
                <h4 class="alert-heading">Advertencia!</h4>
                No se puede cambiar el estado de una fase cuando el proyecto se encuentra en estado pendiente!
            </div>
        {% else %}
            <div class="card" style="padding-top: 50px; padding-left: 200px; padding-right: 200px">
            <div class="card-header">
                <strong>Cambio de estado - Fase "{{ fase.nombre }}"</strong>
            </div>
            <div class="card-body card-block">
                <form action="#" method="post" enctype=" multipart
                    /form-data" class="form-horizontal">
                    {% csrf_token %}
                    <div class="row form-group">
                        <div class="col col-md-3">{{ form.estado.label }}</div>
                        <div class="col-12 col-md-9">{{ form.estado }}</div>
                    </div>
                    <div class="text-center">
                        <p style="color: #1a1a1a"><small>Si no aparece la opcion 'Cerrada' es porque no se cumplen los requisitos para cerrar la fase.</small></p>
                        <button type="submit" class="btn btn-success">Guardar</button>
                        <a class="btn btn-secondary" href="#" onclick="window.history.back()">Cancelar</a>
                    </div>
                </form>
            </div>
            </div>
        {% endif %}
{% endblock content %}

templates/fase/fase_detalles.html
{% extends 'base/base.html' %}
{% block title %} Detalles fase {% endblock%}

{% block content %}
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'proyecto:detail' pk=proyecto.pk %}">
      Proyecto {{ proyecto }}</a></li>
      <li class="breadcrumb-item active">Fase {{ fase }} </li>
    </ol>
    <div class="card">
        <div class="card-header">
            <strong>Fase {{ fase.nombre }} - Detalles</strong>
        </div>
        <div class="card-body card-block">
            <h4>Nombre: <small class="text-muted">{{ fase.nombre }}</small></h4>
            <h4>Descripcion: <small class="text-muted">{{ fase.descripcion }}</small></h4>
            <h4>Fecha de creacion: <small class="text-muted">{{ fase.fecha_creacion }}</small></h4>
            <h4>Estado: <small class="text-muted">{{ fase.estado }}</small></h4>
            <h4>Proyecto: <small class="text-muted">{{ fase.proyecto.nombre }}</small></h4>
            <h4>Miembros:
                <ul style="list-style: circle">
                    {% for miembro in fase.miembros.all %}
                        <li><small class="text-muted">{{ miembro }}:</small></li>
                    {% endfor %}
                </ul>
            </h4>
            <button type="button" class="btn btn-link" onclick="window.history.back()">Volver</button>
        </div>
    </div>
{% endblock content %}

templates/fase/fase_lista.html
{% extends 'base/base.html' %}
{% block title %} Listar fases {% endblock %}

{% block content %}
    <ol class="breadcrumb">      
      <li class="breadcrumb-item active">Proyecto {{ proyecto }}</li>            
    </ol>
    
    <h1 style="text-align: center">Fases del proyecto {{ proyecto.nombre }}</h1>
    {% if page_obj %}
    <form method="GET" action="{% url 'fase:search' proyecto.id %}">
        <div id="custom-search-input">
            <div class="input-group col-md-12">
                <input type="text" class="form-control search-users"
                       placeholder="Ingrese el nombre o de la descripci&oacute;n de la fase." name="buscar"
                       value="{{ request.GET.buscar }}">
                <span class="input-group-list">
                                <i class="icon icon-search"></i>
                                <button type="submit" class="btn btn-success btn-search-users">Buscar</button>
                            </span>
            </div>
        </div>
    </form>

    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Descripcion</th>
            <th scope="col">Estado</th>
            <th scope="col">Fecha de Creacion</th>
            <th scope="col" style="text-align: center">Opciones</th>
        </tr>
        </thead>
        <tbody>

            {% for fase in page_obj %}
                <tr>
                    <td>{{ fase.nombre }}</td>
                    <td>{{ fase.descripcion }}</td>
                    <td>{{ fase.estado }}</td>
                    <td>{{ fase.fecha_creacion }}</td>
                    <td>
                     {% if fase.estado != 'Cerrada' %}   
                        <div class="dropdown" style="display: inline">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                                    data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">
                                Item
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="{% url 'item:crear_item' fase.id %}">Crear</a>
                                <a class="dropdown-item" href="{% url 'item:item_lista' fase.id %}">Lista de
                                    items</a>
                            </div>
                        </div>
                        <div class="dropdown" style="display: inline">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                                    data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">
                                Linea base
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item"
                                   href="{% url 'linea_base:crear_linea' id_fase=fase.id %}">Crear</a>
                                <a class="dropdown-item" href="{% url 'linea_base:linea_lista' fase.id %}">Lista de
                                    LB</a>
                            </div>
                        </div>
                        <div class="dropdown" style="display: inline">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                                    data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">
                                Roles
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item"
                                   href="{% url 'rol:rol_crear' id_fase=fase.id %}">Crear</a>
                                <a class="dropdown-item" href="{% url 'rol:rol_lista' id_fase=fase.id %}">Lista de
                                    Roles</a>
                            </div>
                        </div>
                        <div class="dropdown" style="display: inline">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                                    data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">
                                Tipos de item
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item"
                                   href="{% url 'tipo_item:crear_tipo_item' id_fase=fase.id %}">Crear</a>
                                <a class="dropdown-item" href="{% url 'tipo_item:tipo_item_lista' fase.id %}">Listar</a>
                                <a class="dropdown-item" href="{% url 'tipo_item:listar_importacion' fase.id %}">Importar tipo item</a>

                                {#                                <a class="dropdown-item" href="{% url 'fase:fase_eliminar' fase.id proyecto.id %}">Eliminar</a>#}
                            </div>
                        </div>
                    {% endif %}

                        <div class="dropdown" style="display: inline">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                                    data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">
                                Mas
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="{% url 'fase:fase_detalles' fase.id %}">Detalles</a>
                              {% if fase.estado == 'Abierta' %}
                                <a class="dropdown-item"
                                   href="{% url 'fase:fase_cambiar_estado' fase.id proyecto.id %}">Cambiar estado</a>
                                <a class="dropdown-item" href="{% url 'fase:fase_modificar' fase.id proyecto.id %}">Editar</a>
                              {% endif %}
                                {% if proyecto.estado != 'Iniciado' %}
                                    <a class="dropdown-item" href="{% url 'fase:fase_eliminar' fase.id proyecto.id %}">Eliminar</a>
                                {% endif %}
                                {% if proyecto.estado != 'Pendiente' %}
                                    <a class="dropdown-item" href="{% url 'fase:reporte_fase' fase.id %}">Generar Reporte Fase</a>
                                {% endif %}
                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}

        </tbody>
    </table>

    <div class="text-center">
        <div class="pagination">
                <span class="step-links">

                    <span class="current">
                          <li>Pagina {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</li>
                    </span>
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; Inicio</a>
                        <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
                    {% endif %}

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                    {% endif %}
                </span>
        </div>
    </div>
    {% else %}
        <br><br>
        <h3 style="text-align: center" class="table-warning">Aun no se han creado fases en el proyecto</h3>

    {% endif %}
    <center><a type="button" class="btn btn-secondary" href="{% url 'proyecto:detail' proyecto.id %}">Volver al proyecto</a></center>
{% endblock content %}

templates/fase/fase_opciones.html
{% extends 'base/base.html' %}
{% block title %} Gestión de Fases {% endblock%}

{% block content %}
	<div class="list-group">
	  <a href="{% url 'fase:crear_fase' %}" class="list-group-item list-group-item-action">Crear fase</a>
	  <a href="{% url 'fase:fase_lista' %}" class="list-group-item list-group-item-action">Lista de fases</a>
	</div>
{% endblock content %}