SGCAS/urls.py
from django.conf.urls import url, handler403
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.views.generic import TemplateView
from SGCAS.settings import base, desarrollo
# from django.contrib.auth.views import logout_then_login


handler403 = 'apps.rol.views.handler403'
# se asigna la nueva ruta de la vista creada para el error 403

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="account/index.html")),
    url(r'^account/', include('allauth.urls')),
    path('usuario/', include('apps.usuario.urls', namespace='usuario')),
    path('rol/', include(('apps.rol.urls', 'rol'), namespace='rol')),
    path('item/', include(('apps.item.urls', 'item'), namespace='item')),
    path('tipo_item/', include(('apps.tipo_item.urls', 'tipo_item'), namespace='tipo_item')),
    path('mensajes/', include(('apps.mensajes.urls', 'mensajes'), namespace='mensajes')),
    path('gestion-proyecto/', include(('apps.proyecto.urls', 'proyecto'), namespace='proyecto')),
    path('comite/', include(('apps.comite.urls', 'comite'), namespace='comite')),
    path('fase/', include(('apps.fase.urls', 'fase'), namespace='fase')),
    url(r'^faq/', login_required(TemplateView.as_view(template_name='faq.html'))),
    path('linea_base/', include(('apps.linea_base.urls', 'linea_base'), namespace='linea_base')),
]

if desarrollo.DEBUG:
    urlpatterns += static(desarrollo.MEDIA_URL, document_root=desarrollo.MEDIA_ROOT)
    # urlpatterns += static(desarrollo.STATIC_URL, document_root=base.STATIC_ROOT)

"""
    path("signup/", views.signup, name="account_signup"),
    path("login/", views.login, name="account_login"),
<<<<<<< HEAD

    path("logout/", views.logout, name="account_logout"),
>>>>>>> origin/guillermo

=======
<<<<<<< HEAD
    path('logout/', views.logout, name="account_logout"),
=======
    path("logout/", views.logout, name="account_logout"),
>>>>>>> origin/guillermo
>>>>>>> 9de1af86a9d6e911ed13280b7cc8d7d8dc58a668
    path("password/change/", views.password_change,
         name="account_change_password"),
    path("password/set/", views.password_set, name="account_set_password"),
    path("inactive/", views.account_inactive, name="account_inactive"),

    # E-mail
    path("email/", views.email, name="account_email"),
    path("confirm-email/", views.email_verification_sent,
         name="account_email_verification_sent"),
    re_path(r"^confirm-email/(?P<key>[-:\w]+)/$", views.confirm_email,
            name="account_confirm_email"),

    # password reset
    path("password/reset/", views.password_reset,
         name="account_reset_password"),
    path("password/reset/done/", views.password_reset_done,
         name="account_reset_password_done"),
    re_path(r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
            views.password_reset_from_key,
            name="account_reset_password_from_key"),
    path("password/reset/key/done/", views.password_reset_from_key_done,
         name="account_reset_password_from_key_done"),
"""

apps/comite/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required

# === Importamos las vistas basadas en clases y en funciones del codigo fuente de views.py ===

# **Vistas basadas en clases**

# **1.CreateComite :** Vista que despliega la creación de un comité<br/>
# **2.UpdateComite :** Vista que despliega la modificación de un comité<br/>
# **3.DeleteComite :** Vista que despliega eliminar un comité<br/>
from apps.comite.views import CreateComite, UpdateComite, DeleteComite, success, lista_solicitudes, voto_favor, \
    voto_contra, DetailComite, auditoria_solicitudes, solicitud_item, DetailComite,reporte_solicitud_rango, render_pdf_view

app_name = 'comite'
# ** Dirección de URL desplegar las vistas en la dirección de plantillas respectivamente. **
urlpatterns = [
    url(r'^crear-comite/(?P<_id>\d+)/$', login_required(CreateComite.as_view()), name='create'),
    url(r'^editar-comite/(?P<pk>\d+)/$',login_required(permission_required('comite.editar_comite', raise_exception=True)(UpdateComite.as_view())),name='update'),
    url(r'^ver-comite/(?P<pk>\d+)/$',login_required(permission_required('comite.ver_comite', raise_exception=True)(DetailComite.as_view())),name='detail'),
    url(r'^eliminar-comite/(?P<pk>\d+)/$',login_required(permission_required('comite.eliminar_comite', raise_exception=True)(DeleteComite.as_view())),name='delete'),
    url(r'^detalles-comite/(?P<pk>\d+)/$',login_required(permission_required('comite.ver_comite', raise_exception=True)(DetailComite.as_view())),name='detail'),
    url(r'^operacion-exitosa/$', login_required(success), name='success'),
    url(r'^solicitud-item/(?P<pk>\d+)/$', login_required(solicitud_item), name='solicitud_item'),
    url(r'^lista-solicitudes/(?P<pk>\d+)/$', login_required(lista_solicitudes), name='solicitudes'),
    url(r'^voto_favor/(?P<pk>\d+)/$', login_required(voto_favor), name='voto_favor'),
    url(r'^voto_contra/(?P<pk>\d+)/$', login_required(voto_contra), name='voto_contra'),
    url(r'^auditoria-solicitudes/(?P<pk>\d+)/$', login_required(auditoria_solicitudes), name='auditoria'),
    url(r'^generar-reporte/(?P<id_proyecto>\d+)/(?P<id_comite>\d+)/$', login_required(render_pdf_view), name='reporte_solicitud'),
    url(r'^generar-reporte-por-rango/(?P<id_proyecto>\d+)/(?P<id_comite>\d+)/$', login_required(reporte_solicitud_rango), name='reporte_solicitud_rango'),
]

# **Atras** : [[tests.py]]

# **Siguiente** : [[views.py]]

# === Indice de la documentación de la Aplicación Comité  === <br/>
# 1.admin   : [[admin.py]]<br/>
# 2.apps    : [[apps.py]]<br/>
# 3.forms   : [[forms.py]]<br/>
# 4.models  : [[models.py]]<br/>
# 5.tests   : [[tests.py]]<br/>
# 6.urls    : [[urls.py]]<br/>
# 7.views   : [[views.py]]<br/>

# Regresar al menu principal : [Menú Principal](../../docs-index/index.html)

apps/fase/urls.py
from django.conf.urls import url
from apps.fase.views import *
from django.contrib.auth.decorators import login_required, permission_required
# === Importamos las vistas basadas en clases y en funciones del codigo fuente de views.py ===

urlpatterns = [
    url(r'^opciones/', login_required(fase_opciones), name='fase_opciones'),
    url(r'^results/(?P<_id>\d+)/$', login_required(permission_required('fase.listar_fase', raise_exception=True)(search)), name='search'),
    url(r'^cambiar_estado/(?P<id_fase>\d+)/(?P<_id>\d+)/$', login_required(cambiar_estado_fase), name='fase_cambiar_estado'),
    url(r'^fase_detalles/(?P<id_fase>\d+)/$', login_required(fase_detalles), name='fase_detalles'),
    url(r'^crear/(?P<_id>\d+)/$', login_required(permission_required('fase.crear_fase',raise_exception=True)(FaseCrear.as_view())), name='crear_fase'),
    url(r'^lista/(?P<_id>\d+)/$', login_required(permission_required('fase.listar_fase', raise_exception=True)(lista_fase)), name='fase_lista'),
    url(r'^eliminar/(?P<id_fase>\d+)/(?P<_id>\d+)/$', login_required(eliminar_fase), name='fase_eliminar'),
    url(r'^editar/(?P<id_fase>\d+)/(?P<_id>\d+)/$', login_required(fase_modificar), name='fase_modificar'),
    url(r'^generar-reporte/(?P<id_fase>\d+)/$', login_required(render_pdf_view), name='reporte_fase'),
]

# **Volver atras** : [[forms.py]]

# **Ir a la documentación de vistas del modulo fase** : [[views.py]]

# === Indice de la documentación de la Aplicación fase  === <br/>
# 1.admin   : [[admin.py]]<br/>
# 2.apps    : [[apps.py]]<br/>
# 3.forms   : [[forms.py]]<br/>
# 4.models  : [[models.py]]<br/>
# 5.tests   : [[tests.py]]<br/>
# 6.urls    : [[urls.py]]<br/>
# 7.views   : [[views.py]]<br/>

# Regresar al menu principal : [Menú Principal](../../docs-index/index.html)

apps/item/urls.py
from django.conf.urls import url
from apps.item.views import *
from django.contrib.auth.decorators import login_required

# === Importamos las vistas basadas en clases y en funciones del codigo fuente de views.py ===

# **Vistas : **

# **1.Cambiar estado de un item :** Vista que despliega el cambio de estado de un item<br/>
# **2.Gestión de items          :** Vista que despliega la gestión de items<br/>
# **3.Crea item                 :** Vista que despliega la creación de un item<br/>
# **4.Importar tipo de item     :** Vista que despliega los tipos de items para importarlos<br/>
# **5.Atributos de un tipo_item :** Vista que despliega los atributos para un tipo de item<br/>
# **6.Listar items              :** Vista que despliega la lista de items en una fase<br/>
# **7.Eliminar item             :** Vista que despliega eliminar un item<br/>
# **8.Editar                    :** Vista que despliega editar un item<br/>
# **9.Editar tipo de item       :** Vista que despliega editar un tipo de item<br/>
# **10.Editar atributos         :** Vista que despliega editar los datos de un atributo de un tipo_item<br/>


# ** Dirección de URL desplegar las vistas en la dirección de plantillas respectivamente. **
urlpatterns = [
    url(r'^cambiar_estado/(?P<pk>\d+)/$', login_required(item_cambiar_estado), name='item_cambiar_estado'),
    url(r'^item_detalles/(?P<pk>\d+)/(?P<id_fase>\d+)/$', login_required(item_detalles), name='item_detalles'),
    url(r'^versiones/(?P<pk>\d+)/(?P<id_fase>\d+)/$', login_required(item_versiones), name='versiones'),
    url(r'^calculo-de-impacto/(?P<pk>\d+)/$', login_required(calculo_impacto), name='calculo_impacto'),
    url(r'^trazabilidad-de-item/(?P<pk>\d+)/$', login_required(trazabilidad), name='trazabilidad'),
    url(r'^restaurar_version/(?P<pk>\d+)/(?P<id_fase>\d+)/$', login_required(restaurar_version),
        name='restaurar_version'),
    url(r'^fases_relaciones/(?P<pk>\d+)/$', login_required(fases_rel), name='fases_rel'),
    url(r'^relaciones/(?P<pk>\d+)/(?P<id_fase>\d+)/$', login_required(relaciones), name='relaciones'),
    url(r'^crear/(?P<id_fase>\d+)/$', login_required(crear_item_basico), name='crear_item'),
    url(r'^importar_tipo_item/(?P<pk>\d+)/$', login_required(item_importar_ti), name='importar_tipo_item'),
    url(r'^atributos/(?P<pk>\d+)/$', login_required(item_set_atributos), name='set_atributos'),
    url(r'^results/(?P<id_fase>\d+)/$', login_required(search), name='search'),
    url(r'^lista/(?P<id_fase>\d+)/$', login_required(item_lista_fase), name='item_lista'),
    url(r'^eliminar/(?P<pk>\d+)/(?P<id_fase>\d+)/$', login_required(item_eliminar), name='item_eliminar'),
    url(r'^editar/(?P<pk>\d+)/(?P<id_fase>\d+)/$', login_required(item_modificar_basico), name='item_modificar'),
    url(r'^editar_import_ti/(?P<pk>\d+)/$', login_required(item_modificar_ti), name='item_modificar_import_ti'),
    url(r'^editar_atributos_ti/(?P<pk>\d+)/$', login_required(item_modificar_atributos), name='item_modificar_atr_ti'),
]
# **Atras** : [[tests.py]]

# **Siguiente** : [[views.py]]

# === Indice de la documentación de la Aplicación item  === <br/>
# 1.admin   : [[admin.py]]<br/>
# 2.apps    : [[apps.py]]<br/>
# 3.forms   : [[forms.py]]<br/>
# 4.models  : [[models.py]]<br/>
# 5.tests   : [[tests.py]]<br/>
# 6.urls    : [[urls.py]]<br/>
# 7.views   : [[views.py]]<br/>

# Regresar al menu principal : [Menú Principal](../../docs-index/index.html)

apps/item/models.py
from django.db import models
from apps.usuario.models import User
from django.core.exceptions import ValidationError
from django.db.models import Q
import datetime

from apps.fase.models import Fase
from apps.tipo_item.models import TipoItem

# **Estados existentes de un item**
"""
1.En Desarrollo : el item se encuentra disponible para su edición 
2.Aprobado      : el item se encuentra aprobado
3.Desactivado   : el item se encuentra desactivado 
4.Revisión      : el item se encuentra en estado de revisión par su posterior aprobación
5.LineaBase     : el item se encuentra en una linea base 
"""
item_estado = [
    ('Desarrollo', 'Desarrollo'),
    ('Aprobado', 'Aprobado'),
    ('Revision', 'Revision'),
]


# === Clase que modela el concepto de un comite para los proyectos ===
class Item(models.Model):
    # 1. **nombre**: Campo para dar asignar un nombre al item.<br/>
    # 2. **descripción**: Campo para describir brevemente información respecto al item.<br/>
    # 3. **fecha_creacion**: campo para registrar la fecha de creación de un item.<br/>
    # 4. **estado**: campo que registra los distintos estados que pueda tener un item.<br/>
    # 5. **costo**: campo que registra el costo de un item.<br/>
    # 6. **usuarios_a_cargo**: Relación de MuchosAmuchos con los miembros de una para estar a cargo de ese item.<br/>
    # 7. **archivo**: campo que almacena un archivo adjunto al item.<br/>
    # 8. **fase**: Relación con la fase donde va a corresponder.<br/>
    # 9. **tipo_item**: campo donde asigna un tipo de item .<br/>
    # 10. **boolean**: atributo boolean.<br/>
    # 11. **char**: atributo char.<br/>
    # 12. **date**: atributo date.<br/>
    # 13. **numerico**: atributo numerico.<br/>
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=50)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    estado = models.CharField(max_length=30, choices=item_estado, default='Desarrollo')
    en_linea_base = models.BooleanField(default=False)
    costo = models.PositiveIntegerField()
    usuarios_a_cargo = models.ManyToManyField(User, blank=True)
    archivo = models.FileField(null=True, blank=True)
    file_url_cloud = models.CharField(max_length=200, null=True, blank=True)
    fase = models.ForeignKey(Fase, on_delete=models.CASCADE, null=True)
    tipo_item = models.ForeignKey(TipoItem, on_delete=models.CASCADE, null=True, default='')
    impacto = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    ### Atributos para tipos de item ###
    boolean = models.BooleanField(default=False)
    char = models.CharField(max_length=100, default='', blank=True)
    date = models.DateField(null=True, blank=True)
    numerico = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    ### Atributos para relaciones ###
    padres = models.ManyToManyField('self', symmetrical=False, blank=True, related_name='padre')
    hijos = models.ManyToManyField('self', symmetrical=False, blank=True, related_name='hijo')
    antecesores = models.ManyToManyField('self', symmetrical=False, blank=True, related_name='antecesor')
    sucesores = models.ManyToManyField('self', symmetrical=False, blank=True, related_name='sucesor')
    ### Atributos para el versionado
    nro_version = models.DecimalField(max_digits=10, decimal_places=1, default=0.1)
    versiones = models.ForeignKey('self', on_delete=models.CASCADE, null=True)
    last_release = models.BooleanField(default=True)
    ultima_modificacion = models.DateTimeField(auto_now=True)

    class Meta:
        default_permissions = ()  # se deshabilita la creacion de permisos por defecto de django
        permissions = [
            # ("crear_item", "crear_item"),
            # ("aprobar_item", "aprobar_item"),
            # ("editar_item", "editar_item"),
            # ("eliminar_item", "eliminar_item"),
            # ("relacionar_item", "relacionar_item"),
            # ("restaurar_item_version", "restaurar_item_version"),
            # ("ver_item", "ver_item"),
            # ("ver_versiones_item", "ver_versiones_item"),
            # ("item_modificar_atributos", "item_modificar_atributos"),
            # ("cambiar_estado_item", "cambiar_estado_item"),
            # ("item_modificar_ti", "item_modificar_ti"),
            # ("item_modificar_atributos_ti", "item_modificar_atributos_ti"),
            # ("item_modificar_import_ti", "item_modificar_import_ti"),
            # ("listar_item_de_fase", "listar_item_de_fase"),
            # ("calcular_impacto", "calcular_impacto"),
            # ("ver_trazabilidad", "ver_trazabilidad"),

            ("crear_item", "Puede crear item"),
            ("editar_item", "Puede editar item"),
            ("listar_item", "Puede listar item"),
            ("ver_item", "Puede ver item"),
            ("eliminar_item", "Puede eliminar item"),
            ("cambiar_estado_item", "Puede cambiar estado item"),
            ("relacion_item", "Puede gestionar relacion de item"),
            ("calcular_impacto", "Puede calcular impacto item"),
            ("ver_trazabilidad", "Puede ver trazabilidad item"),
            ("versiones_item", "Puede versionar item"),
            ("restaurar_item_version", "Puede restaurar version item"),
            ("item_modificar_atributos", "Puede modificar atributos item"),
            ("item_modificar_ti", "Puede modificar TI de item"),
            ("item_modificar_atributos_ti", "Puede modificar atributos ti de item"),
            ("item_modificar_import_ti", "Puede modificar  import ti de item"),
        ]

        verbose_name = 'Item'
        verbose_name_plural = 'Items'

    def __str__(self):
        """
        **Función para asignar un alias al modelo item**<br/>
        **:return:** el nombre comité<br/>
        """
        return self.nombre

  

# **Volver atras** : [[forms.py]]

# **Ir a la documentación de pruebas unitarias del modulo item** : [[tests.py]]

# === Indice de la documentación de la Aplicación item  === <br/>
# 1.admin   : [[admin.py]]<br/>
# 2.apps    : [[apps.py]]<br/>
# 3.forms   : [[forms.py]]<br/>
# 4.models  : [[models.py]]<br/>
# 5.tests   : [[tests.py]]<br/>
# 6.urls    : [[urls.py]]<br/>
# 7.views   : [[views.py]]<br/>

# Regresar al menu principal : [Menú Principal](../../docs-index/index.html)

templates/item/item_fases_relaciones.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="card" style="padding-top: 50px; padding-left: 200px; padding-right: 200px">
        <div class="card-header">
            <strong>Fases - [ {{ item }} ∈ {{ fase }} ]</strong>
        </div>
        <div class="card-body card-block">
            {% for fase in fases_proyecto %}
                <a type="button" class="btn btn-secondary"
                   href="{% url 'item:relaciones' item.id fase.id %}">{{ fase.nombre }}</a><br>
            {% endfor %}
            <a class="btn btn-link" href="#" onclick="window.history.back()">Cancelar</a>
        </div>
    </div>
{% endblock %}

templates/item/item_opciones.html
{% extends 'base/base.html' %}
{% block title %} Gestión de Item {% endblock%}

{% block content %}
    <div class="list-group">
	  <a href="{% url 'item:crear_item' %}" class="list-group-item list-group-item-action">Crear item</a>
	  <a href="{% url 'item:item_lista' %}" class="list-group-item list-group-item-action">Lista de items</a>
	</div>
{% endblock content %}

templates/item/item_versiones.html
{% extends 'base/base.html' %}
{% block title %} Versiones de item {% endblock %}

{% block content %}
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'proyecto:detail' pk=proyecto.pk %}">
      Proyecto {{ proyecto }}</a></li>  
      <li class="breadcrumb-item"><a href="#" onclick="window.history.back()">Fase {{ fase }}</a></li>
      <li class="breadcrumb-item active">Item {{ item }} </li>   
    </ol>

<!--    {#    <form method="GET" action="{% url 'item:search' fase.id %}">#}-->
<!--    {#        <div id="custom-search-input">#}-->
<!--    {#            <div class="input-group col-md-12">#}-->
<!--    {#                <input type="text" class="form-control"#}-->
<!--    {#                       placeholder="Ingrese el nombre o la descripci&oacute;n del &iacute;tem." name="buscar"#}-->
<!--    {#                       value="{{ request.GET.buscar }}">#}-->
<!--    {#                <span class="input-group-list">#}-->
<!--    {#                            <i class="icon icon-search"></i>#}-->
<!--    {#                            <button type="submit" class="btn btn-success">Buscar</button>#}-->
<!--    {#                        </span>#}-->
<!--    {#            </div>#}-->
<!--    {#        </div>#}-->
<!--    {#    </form>#}-->

    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Descripcion</th>
            <th scope="col">Estado</th>
            <th scope="col">Fecha de Creacion</th>
            <th scope="col">Archivo</th>
            <th scope="col">Versión</th>
            <th scope="col" style="text-align: center">Opciones</th>
        </tr>
        </thead>
        <tbody>

        {% if versiones %}    
            {% for item in versiones %}
                <tr>
                    <td>{{ item.nombre }}</td>
                    <td>{{ item.descripcion }}</td>
                    <td>{{ item.estado }}</td>
                    <td>{{ item.fecha_creacion }}</td>
                    <td>
                        {% if item.archivo %}
                            <a href="{{ item.file_url_cloud }}" target="_blank" class="btn btn-outline-primary btn-sm">Ver
                            archivo</a>
                        {% else %}
                            No adjunto.
                        {% endif %}
                    </td>
                    <td>{{ item.nro_version }}</td>
                    <td>
                        <a type="button" class="btn btn-success"
                       href="{% url 'item:restaurar_version' item.id item.fase.id %}">Restaurar versión</a>
                        <a type="submit" class="btn btn-secondary"
                       href="{% url 'item:item_detalles' item.id item.fase.id %}">Detalles</a>
                    </td>
                </tr>
            {% endfor %}

            {% else %}
                <br>
                <h2>No existen versiones de &eacute;ste &iacute;tem.</h2>
            {% endif %}

        </tbody>

    </table>    

        <div class="text-center">
            <div class="pagination">
                <span class="step-links">
                    
                    <span class="current">
                          <li>Pagina {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</li>
                   </span>
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; Inicio</a>
                        <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
                    {% endif %}
    
                   {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                    {% endif %}
                </span>
            </div>
        </div>
      
<a type="button" class="btn btn-link" href="{% url 'item:item_lista' fase.id %}">Volver a lista de items</a>

{% endblock content %}

templates/item/list_busqueda.html
{% extends 'base/base.html' %}
{% block title %}  B&uacute;squeda de &Iacute;tems{% endblock%}

{% block content %}
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'proyecto:detail' pk=proyecto.pk %}">
      Proyecto {{ proyecto }}</a></li>
      <li class="breadcrumb-item active">Fase {{ fase }} </li>
    </ol>
<form method="GET" action="{% url 'item:search' fase.id %}">
        <div id="custom-search-input">
                    <div class="input-group col-md-12">
                        <input type="text" class="form-control search-users" placeholder="Ingrese una parte del nombre o de la descripci&oacute;n del &iacute;tem." name="buscar" value="{{ request.GET.buscar }}">
                        <span class="input-group-list">
                            <i class="icon icon-search"></i>
                            <button type="submit" class="btn btn-success btn-search-users">Buscar</button>
                        </span>
                    </div>
                </div>   
</form>
   <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">Nombre</th>
            {#            <th scope="col">Descripcion</th>#}
            <th scope="col">Estado</th>
            <th scope="col">Costo</th>
            <th scope="col">Archivo</th>
            <th scope="col">Tipo de Item</th>
            <th scope="col">Versión</th>
            <th scope="col" style="text-align: center">Opciones</th>
        </tr>
        </thead>
        <tbody>
       {% for item in page_obj %}
            <tr>
                <td>{{ item.nombre }}</td>
                {#                <td>{{ item.descripcion }}</td>#}
                <td>{{ item.estado }}</td>
                <td>{{ item.costo }}
                    {% if item.costo == 1 %}
                        hora.
                    {% else %}
                        horas.
                    {% endif %}
                </td>
                <td>
                    {% if item.archivo %}
                        <a href="{{ item.file_url_cloud }}" target="_blank" class="btn btn-outline-primary btn-sm">Visualizar</a>
                    {% else %}
                        No adjunto.
                    {% endif %}
                </td>
                <td>{{ item.tipo_item }}</td>
                <td>{{ item.nro_version }}</td>
                <td>
                    {% if not item.en_linea_base and item.estado == 'Desarrollo'%}
                    <a type="button" class="btn btn-warning"
                       href="{% url 'item:item_modificar' item.id item.fase.id %}">Editar</a>

                    <a type="submit" class="btn btn-danger"
                       href="{% url 'item:item_eliminar' item.id item.fase.id %}">Eliminar</a>
                    {% endif %}
                    {% if not item.en_linea_base and item.estado == 'Revision'%}
                    <a type="button" class="btn btn-warning"
                       href="{% url 'item:item_modificar' item.id item.fase.id %}">Editar</a>        
                    {% endif %}
                    <div class="dropdown" style="display: inline">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                                data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                            Mas
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="{% url 'item:item_detalles' item.id item.fase.id %}">Detalles</a>
                            <a class="dropdown-item" href="{% url 'item:item_cambiar_estado' item.id %}">Cambiar
                                estado</a>
                            {% if not item.en_linea_base and item.estado == 'Desarrollo'%}
                            <a class="dropdown-item" href="{% url 'item:fases_rel' item.id %}">Relaciones</a>
                            {% endif %}
                            <a class="dropdown-item" href="{% url 'item:calculo_impacto' item.id %}">Cálculo de
                                impacto</a>
                            <a class="dropdown-item" href="{% url 'item:trazabilidad' item.id %}">Trazabilidad</a>
                            {% if not item.en_linea_base and item.estado == 'Desarrollo' %}
                            <a class="dropdown-item" href="{% url 'item:versiones' item.id item.fase.id%}">Versiones</a>
                            {% endif %}
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


    <div class="text-center">
        <div class="pagination">
            <span class="step-links">

                <span class="current">
                      <li>Pagina {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</li>
                </span>
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; Inicio</a>
                    <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
                {% endif %}

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                {% endif %}
            </span>
        </div>
    </div>

    <a type="button" class="btn btn-link" href="{% url 'fase:fase_lista' _id=proyecto.id %}">Volver a lista de fases</a>
{% endblock content %}